test/policy-collection/policy_gatekeeper_operator_downstream_test.go, test/policy-collection/policy_gatekeeper_operator_test.go
https://github.com/open-cluster-management/backlog/issues/10074
https://github.com/open-cluster-management/backlog/issues/10096
https://github.com/open-cluster-management/backlog/issues/10131
https://github.com/open-cluster-management/backlog/issues/10139
https://github.com/open-cluster-management/backlog/issues/10142
=> should patch webhook on managed cluster

test/policy-collection/policy_gatekeeper_operator_downstream_test.go, test/policy-collection/policy_gatekeeper_operator_test.go
https://travis-ci.com/github/open-cluster-management/governance-policy-framework/jobs/491266152#L2242
=> increase the time out for gatekeeper invalid ns scenario

build/run-e2e-tests.sh, deploy/config-policy-controller/clusterrole.yaml, deploy/config-policy-controller/clusterrole_binding.yaml, deploy/config-policy-controller/operator.yaml, deploy/config-policy-controller/service_account.yaml
Keep consistency with https://github.com/open-cluster-management/config-policy-controller/pull/101/files
=> rename config policy controller

test/e2e/gatekeeper_test.go
https://travis-ci.com/github/open-cluster-management/governance-policy-framework/jobs/495976218#L865
https://travis-ci.com/github/open-cluster-management/governance-policy-framework/jobs/495884604#L1353
=> increase time out for 8sRequiredLabels ns-must-have-gk check

test/resources/configuration_policy/role-policy-e2e.yaml, test/resources/configuration_policy/role-policy-musthave-compliant.yaml
This reverts commit f0cc7a1974d8f8e47688595e7a406328733ffc4f.
=> Revert "fix order in checked lists to avoid failures (#96)"

README.md, doc/configuration-policy/README.md, doc/configuration-policy/audit/audit-pod-kind-field-filter.yaml, doc/configuration-policy/audit/audit-pod-kind.yaml, doc/configuration-policy/audit/audit-role-multiple-ns.yaml, doc/configuration-policy/audit/audit-role-single-ns.yaml, doc/configuration-policy/audit/role-original.yaml, doc/configuration-policy/create/create-role-multiple-ns.yaml, doc/configuration-policy/create/create-role-single-ns.yaml, doc/configuration-policy/delete/delete-role-multiple-ns.yaml, doc/configuration-policy/delete/delete-role-single-ns.yaml, doc/configuration-policy/gatekeeper/gatekeeper-install.yaml, doc/configuration-policy/gatekeeper/gatekeeper-policy-sample.yaml, doc/configuration-policy/merge-patch/merge-patch-role-multiple-ns.yaml, doc/configuration-policy/merge-patch/merge-patch-role-single-ns.yaml, doc/configuration-policy/merge-patch/role-original.yaml, doc/configuration-policy/replace-patch/replace-patch-role-multiple-ns.yaml, doc/configuration-policy/replace-patch/replace-patch-role-single-ns.yaml, doc/configuration-policy/replace-patch/role-original.yaml
=> add configuration policy usage doc and examples

doc/configuration-policy/README.md, doc/configuration-policy/create/create-role-multiple-ns.yaml, doc/configuration-policy/create/create-role-single-ns.yaml
=> updates for the demo

test/policy-collection/policy_comp_operator_test.go
https://github.com/open-cluster-management/backlog/issues/12135
=> increase time out for compliance operator test

deploy/crds/policy.open-cluster-management.io_policyautomations_crd.yaml
=> update PolicyAutomation CRD

Makefile
Signed-off-by: Mike Ng <ming@redhat.com>
prereq to https://github.com/open-cluster-management/website/pull/69
=> add community deploy for non kind cluster

test/e2e/configuration_policy_test.go
Signed-off-by: willkutler willkutler@gmail.com
=> wait for patch to complete to stabilize test

test/policy-collection/policy_gatekeeper_operator_downstream_test.go, test/policy-collection/policy_gatekeeper_operator_test.go
https://github.com/open-cluster-management/backlog/issues/12417
=> fix gatekeeper downstream test case

build/patch-dev-images.sh
=> remove console-header

build/patch-cluster.sh, test/policy-collection/policy_comp_operator_test.go
https://github.com/open-cluster-management/backlog/issues/12625
=> increase timeout for compliance operator test

test/policy-collection/policy_gatekeeper_operator_downstream_test.go
=> add polarian id to gatekeeper operator test case

deploy/cert-policy-controller/operator.yaml, deploy/config-policy-controller/operator.yaml, deploy/iam-policy-controller/operator.yaml
Signed-off-by: ckandag <ckandaga@redhat.com>
=> set hubconfig secret

test/policy-collection/policy_comp_operator_test.go
In the middle of the gatekeeper test suite, the admission webhook from
gatekeeper can prevent the namespace from being created with an error.
That means some of the tests run, but then the rest are skipped,
including the clean up tests.
By saving the first time it checks if an openshift-* namespace can be
created, the answer can't change before the clean up runs.
Refs:
- https://github.com/open-cluster-management/backlog/issues/13759
=> Save canCreateOpenshiftNamespaces result

test/policy-collection/policy_gatekeeper_operator_test.go
This will match the namespace in
https://github.com/open-cluster-management/policy-collection/pull/128
=> Change gatekeeper operator namespace

test/policy-collection/policy_comp_operator_test.go
https://github.com/open-cluster-management/backlog/issues/14150
=> increase timeout for compliance operator tests

test/policy-collection/policy_comp_operator_test.go
Attempt to address Compliance test failures in:
- https://github.com/open-cluster-management/backlog/issues/14297
=> Increase timeout to match other pod checks

test/resources/configuration_policy/role-policy-e2e-less.yaml, test/resources/configuration_policy/role-policy-e2e-mismatch.yaml, test/resources/configuration_policy/role-policy-e2e-more.yaml, test/resources/configuration_policy/role-policy-e2e.yaml, test/resources/configuration_policy/role-policy-musthave-compliant.yaml, test/resources/configuration_policy/role-policy-musthave-noncompliant.yaml, test/resources/configuration_policy/role-policy-musthave.yaml, test/resources/configuration_policy/role-policy-mustnothave-compliant.yaml, test/resources/configuration_policy/role-policy-mustnothave-noncompliant.yaml, test/resources/configuration_policy/role-policy-mustnothave.yaml, test/resources/configuration_policy/role-policy-mustonlyhave-compliant.yaml, test/resources/configuration_policy/role-policy-mustonlyhave-noncompliant.yaml, test/resources/configuration_policy/role-policy-mustonlyhave.yaml
=> fix failures due to sort

Makefile, deploy/crds/cluster.open-cluster-management.io_placementdecisions_crd.yaml, deploy/crds/cluster.open-cluster-management.io_placements_crd.yaml, deploy/propagator/clusterrole.yaml
=> add new content to test with new placement

test/policy-collection/policy_gatekeeper_operator_test.go
Some more test updates that were originally in https://github.com/open-cluster-management/governance-policy-framework/pull/126. In particular,
better cleanup logic because the delete behavior in the operator may
change, and the ability to check for the mutation flag regardless of
the order of the command args.
Refs:
- https://github.com/open-cluster-management/backlog/issues/15379
=> [release-2.3] Backport gatekeeper test updates

test/policy-collection/policy_iam_test.go
The OpenShift group and cluster role binding need to be created on the
managed cluster and not the hub.
=> Fix the IAM policy test canary

test/common/common.go
https://github.com/open-cluster-management/backlog/issues/15718
=> Handle exiterror

test/integration/policy_info_metric_test.go
=> fix deletion of clusterrolebinding in metrics test

test/integration/policy_info_metric_test.go
=> fix secret not found error

doc/configuration-policy/README.md
Signed-off-by: Christian Stark <cstark@cstark.muc.csb>
=> added link

test/integration/policy_info_metric_test.go
=> retry get secret until no error

Makefile, build/run-test-image.sh
This reverts commit 460b0946fd5fe4ec9d4dfb6fe7fda1d1dddbd78a in #150
=> Revert "Disable metrics tests from canaries (#150)"

test/integration/integration_suite_test.go, test/integration/policy_info_metric_test.go, test/integration/policy_report_metric_test.go, test/resources/policy_report_metric/compliant.yaml, test/resources/policy_report_metric/noncompliant.yaml
https://github.com/open-cluster-management/backlog/issues/15697
=> add tests to verify policyreport works

test/integration/policy_info_metric_test.go
https://github.com/open-cluster-management/backlog/issues/16546
=> double compliance check timeout for grc metrics test

go.mod, test/common/gvr.go, test/common/user_management.go, test/integration/policy_generator_test.go, test/resources/policy_generator/subscription.yaml
This tests the app lifecycle integration with the policy generator.
=> Add a canary test for the policy-generator

test/integration/policy_report_metric_test.go
https://github.com/open-cluster-management/backlog/issues/16534
=> increase timeout of policyReport metric check to 4 min

test/integration/policy_generator_test.go
Occasionally, the subscription-admin ClusterRoleBinding may not exist
for a short period of time. This ClusterRoleBinding is managed by the
App Lifecycle controllers and thus it is out of the control of this
test to create it. This just accounts for such a delay.
=> Wait for the subscription-admin CRB in the Policy Generator test

test/integration/policy_report_metric_test.go
should make policyReport test more stable, avoiding issues like https://github.com/open-cluster-management/backlog/issues/16766
=> wait for insights client pod with POLLINTERVAL=1 to start

.gitignore, .travis.yml, Makefile, build/run-e2e-tests-policy-framework.sh, build/run-e2e-tests.sh, build/run-test-image.sh, test/e2e/clusterns_label_test.go, test/integration/policy_info_metric_test.go
Addresses:
- https://github.com/open-cluster-management/backlog/issues/16018
=> Update e2e test with debug output

test/integration/policy_report_metric_test.go
to try determine the cause of canary failures
=> policyreport test debug logs

test/policy-collection/policy_gatekeeper_operator_downstream_test.go, test/policy-collection/policy_gatekeeper_operator_test.go
Addresses:
- https://github.com/open-cluster-management/backlog/issues/18217
=> Patch to remove Gatekeeper dryrun

test/policy-collection/policy_gatekeeper_operator_downstream_test.go, test/policy-collection/policy_gatekeeper_operator_test.go
Not a big deal since Policy and PlacementBinding are currently in the same group, but updating just in case it may cause issues in the future.
=> Update group to match resource

test/policy-collection/policy_gatekeeper_operator_test.go
This is a manual cherry-pick of #217
/assign dhaiducek
Addresses 
- https://github.com/open-cluster-management/backlog/issues/18217
=> [release-2.2] Patch to remove Gatekeeper dryrun

Dockerfile.e2etest, build/run-e2e-tests.sh
=> Lock ginkgo gomega version

README.md
Attempt rebuild to pick up:
- https://github.com/open-cluster-management/governance-policy-framework/pull/218
=> [release-2.3] No-op rebuild

.gitignore, Makefile, deploy/template-sync/README.md, deploy/template-sync/debug-logs.yaml, deploy/template-sync/kustomization.yaml
Resolves:
https://github.com/open-cluster-management/backlog/issues/18028
This relates to:
https://github.com/open-cluster-management/governance-policy-template-sync/pull/75
=> Enable debug logs for Policy Template Sync controller

test/policy-collection/policy_comp_operator_test.go, test/policy-collection/policy_gatekeeper_operator_downstream_test.go
https://github.com/open-cluster-management/policy-collection/pull/202
=> Update test case to work with latest policy changes

test/policy-collection/policy_collection_suite_test.go, test/policy-collection/policy_comp_operator_test.go, test/policy-collection/policy_gatekeeper_operator_downstream_test.go, test/policy-collection/policy_gatekeeper_operator_test.go
This is a manual cherry-pick of #228
=> [release-2.3] Update test case to work with latest policy changes

Makefile, deploy/cert-policy-controller/certificatepolicies_crd.yaml
=> [release-2.4] Use 2.4 CRDs for release-2.4 branch

Dockerfile.e2etest, Makefile, README.md, build/ff.sh, build/run-e2e-tests-policy-framework.sh, doc/configuration-policy/README.md, go.mod, test/policy-collection/policy_comp_operator_test.go, test/policy-collection/policy_gatekeeper_operator_downstream_test.go, test/policy-collection/policy_gatekeeper_operator_test.go
=> [release-2.3] Update org references to `stolostron`

CODE_OF_CONDUCT.md, CONTRIBUTING.md, Dockerfile.e2etest, Makefile, README.md, build/ff.sh, build/run-e2e-tests-policy-framework.sh, deploy/crds/README.md, deploy/propagator/README.md, doc/configuration-policy/README.md, doc/development.md, go.mod, test/e2e/cert_policy_test.go, test/e2e/configuration_policy_test.go, test/e2e/e2e_suite_test.go, test/e2e/gatekeeper_test.go, test/e2e/iam_policy_test.go, test/integration/integration_suite_test.go, test/integration/policy_generator_test.go, test/integration/policy_info_metric_test.go, test/integration/policy_report_metric_test.go, test/policy-collection/policy_collection_suite_test.go, test/policy-collection/policy_comp_operator_test.go, test/policy-collection/policy_gatekeeper_operator_downstream_test.go, test/policy-collection/policy_gatekeeper_operator_test.go, test/policy-collection/policy_iam_test.go, test/resources/policy_generator/subscription.yaml
=> [release-2.4] Update org references to `stolostron`

Makefile
=> install policyset crd in Makefile

.travis.yml
=> Do not rebuild and push image again in publish

Makefile, build/clean-up-cluster.sh, build/patch-dev-images.sh, build/run-e2e-tests-ui.sh
- https://github.com/stolostron/backlog/issues/19147
=> [release-2.3] Update GRC UI refs to use new org

Makefile, build/clean-up-cluster.sh, build/patch-dev-images.sh, build/run-e2e-tests-ui.sh, test/integration/policy_generator_test.go
- https://github.com/stolostron/backlog/issues/19147
=> [release-2.4] Update GRC UI refs to use new org

Makefile, build/patch-dev-images.sh, build/run-e2e-tests-ui.sh
- https://github.com/stolostron/backlog/issues/19147
=> [release-2.2] Update GRC UI refs to use new org

Makefile, build/clean-up-cluster.sh, build/patch-dev-images.sh, build/run-e2e-tests-ui.sh, test/integration/policy_generator_test.go
- https://github.com/stolostron/backlog/issues/19147
=> Update GRC UI refs to use new org

Dockerfile.e2etest, Makefile, test/common/gvr.go, test/integration/policy_generator_test.go
https://github.com/stolostron/backlog/issues/19414
=> Add policyset verification

Dockerfile.e2etest, Makefile, test/resources/policy_generator/subscription.yaml
=> Use release-2.4 branch in AppSub

test/integration/integration_suite_test.go, test/integration/policy_info_metric_test.go, test/integration/policy_report_metric_test.go, test/policy-collection/policy_collection_suite_test.go
=> Create/delete user namespace in BeforeSuite and AfterSuite

Makefile, go.mod, go.sum, test/common/user_management.go, test/e2e/cert_policy_test.go, test/e2e/configuration_policy_test.go, test/e2e/e2e_suite_test.go, test/e2e/gatekeeper_test.go, test/e2e/iam_policy_test.go, test/e2e/policySet_e2e_test.go, test/integration/policy_generator_test.go, test/integration/policy_info_metric_test.go, test/integration/policy_report_metric_test.go, test/integration/policy_set_test.go, test/policy-collection/policy_comp_operator_test.go, test/policy-collection/policy_gatekeeper_operator_downstream_test.go, test/policy-collection/policy_gatekeeper_operator_test.go, test/policy-collection/policy_iam_test.go, test/resources/policy_set/disable-policy.yaml, test/resources/policy_set/patch-policy-set.yaml, test/resources/policy_set/statuscheck-1.yaml, test/resources/policy_set/statuscheck-2.yaml, test/resources/policy_set/statuscheck-3.yaml, test/resources/policy_set/statuscheck-4.yaml, test/resources/policy_set/test-policyset.yaml
Signed-off-by: Chunxi Luo chuluo@redhat.com
https://github.com/stolostron/backlog/issues/18398
=> Add e2e test cases for PolicySet

test/policy-collection/policy_gatekeeper_operator_downstream_test.go, test/policy-collection/policy_gatekeeper_operator_test.go
Fixes https://github.com/stolostron/backlog/issues/19992
=> Use `e2etestsuccess` for mutation test 

Makefile, deploy/crds/README.md
https://github.com/stolostron/backlog/issues/19190
=> Upgrade placement API to v1beta1

build/periodic.sh
The `governance-policy-addon-controller` repo was private (it's since become public) and also doesn't have `2.3` or `2.4` images. To address these "false positives", this PR adds:
- An additional check for error messages when querying Quay
- An additional check when an image wasn't found in Pipeline
=> Add additional checks to Prow status script

Makefile, build/clean-up-cluster.sh, build/patch-dev-images.sh, test/policy-collection/policy_gatekeeper_operator_test.go
=> Move over clean up script

build/clean-up-cluster.sh, test/policy-collection/policy_comp_operator_test.go
Fix e2e test failure [here](https://app.travis-ci.com/github/stolostron/governance-policy-framework/jobs/561930373#L2562)
=> Move clean up beforeAll to clean up script

build/run-e2e-tests-policy-framework-prow.sh, build/run-test-image.sh
Not the cleanest, but I think it's better than removing the XML nodes entirely.
Addresses:
- https://github.com/stolostron/backlog/issues/20431
=> Add metadata to BeforeSuite and AfterSuite phases

test/common/gvr.go, test/resources/policy_set/patch-policy-set.yaml, test/resources/policy_set/statuscheck-1.yaml, test/resources/policy_set/statuscheck-2.yaml, test/resources/policy_set/statuscheck-3.yaml, test/resources/policy_set/statuscheck-4.yaml, test/resources/policy_set/test-policyset.yaml
=> Update test cases to use policyset v1beta1

.gitignore, Makefile, build/run-test-kind-prow.sh
=> Expose OLM version as env

build/periodic.sh
- DEFAULT_BRANCH will default to `main` and will not check SHAs since the default branch doesn't publish an image
Also:
- Adds a check for an 'ABORTED' status in addition to 'FAILURE'
- Adds the 'latest-test-image-mirror' job for `grc-ui`
- Updates to use `jq -r` instead of `sed` to get raw strings
=> Add a DEFAULT_BRANCH check

build/wait_for.sh
=> Add time out for wait_for

build/run-e2e-tests-policy-framework.sh, test/integration/policy_namespace_test.go
Fixes https://github.com/stolostron/backlog/issues/20927
=> Use `clientManaged` for namespace check

test/integration/policy-limitmemory_test.go, test/integration/policy_namespace_test.go
Resolves:
https://github.com/stolostron/backlog/issues/20844
=> Add a test for the stable/policy-limitmemory policy

test/integration/policy_certificate_test.go
Resolves:
https://github.com/stolostron/backlog/issues/20843
=> Add a test for the stable/policy-certificate policy

test/integration/policy-limitmemory_test.go
The `userNamespace` only exists on the Hub, so this creates a temporary
namespace on the managed cluster for this test.
=> Create a temporary ns in the policy-limitmemory test

test/integration/policy_comp_operator_test.go
Extract compliance operator scan test code and add cis scan test case.
closes https://github.com/stolostron/backlog/issues/20849
=> Add policy-cis-scan test case

test/integration/integration_suite_test.go, test/integration/policy_certificate_test.go, test/integration/policy_comp_operator_test.go, test/integration/policy_etcdencryption_test.go, test/integration/policy_gatekeeper_operator_downstream_test.go, test/integration/policy_gatekeeper_operator_test.go, test/integration/policy_iam_test.go, test/integration/policy_limitmemory_test.go, test/integration/policy_namespace_test.go
- Use variable for policy-collection base URLs
- Move some common functions to integration_suite_test.go
=> Restructure tests

test/integration/policy_certificate_test.go, test/integration/policy_gatekeeper_operator_downstream_test.go, test/integration/policy_gatekeeper_operator_test.go, test/integration/policy_limitmemory_test.go, test/integration/policy_role_test.go, test/integration/policy_rolebinding_test.go
Resolves https://github.com/stolostron/backlog/issues/20839
Resolves https://github.com/stolostron/backlog/issues/20840
=> Add test cases for policy-role and policy-rolebinding

test/integration/policy_pod_test.go
Addresses:
- https://github.com/stolostron/backlog/issues/20842
=> Add `policy_pod_test.go`

test/policy-collection/policy_comp_operator_test.go
Fixes https://github.com/stolostron/backlog/issues/21129
=> Increase timeout

test/integration/policy_gatekeeper_operator_downstream_test.go, test/integration/policy_gatekeeper_operator_test.go
=> Avoid test panic

test/integration/policy_imagemanifest_test.go
https://github.com/stolostron/backlog/issues/20847
=> add test for stable/policy-imagemanifestvuln

test/integration/policy_psp_test.go
https://github.com/stolostron/backlog/issues/20845
Signed-off-by: Chunxi Luo <chuluo@redhat.com>
=> Implement test case for policy-psp 

.travis.yml, test/integration/policy_etcdencryption_test.go
This should help reduce the grc framework e2e failure in travis
=> Run etcd-encryption in a separate travis stage

test/integration/policy_hub_templates_21440_test.go, test/resources/policy_hub_templates_21440/policy.yaml
Relates:
https://github.com/stolostron/backlog/issues/21440
=> Test that the text/template backport is included

test/integration/policy_hub_templates_21440_test.go, test/resources/policy_hub_templates_21440/policy.yaml
Relates:
https://github.com/stolostron/backlog/issues/21440
This is a modified cherry pick from #320.
=> Test that the text/template backport is included (#320)

build/clean-up-cluster.sh, test/integration/policy_imagemanifest_test.go
=> Update name of operator that changed

Makefile, test/common/common.go, test/common/user_management.go, test/integration/policy_generator_acm_hardening_test.go
=> Cherry pick the additional logs for BVT failure debugging

test/integration/policy_hub_templates_21440_test.go
I've seen some grc e2e failures that are due to the configmaps created
by this test that don't get cleaned up.  I'm not sure why the cleanup
doesn't happen so adding a cleanup function to try to reduce the
failures.  Example failure:
https://app.travis-ci.com/github/stolostron/governance-policy-framework/jobs/569705935#L498
=> GRC e2e is failing often when these configmaps are no cleaned up

Makefile, build/run-e2e-tests-policy-framework-prow.sh
Addressses:
- https://github.com/stolostron/backlog/issues/21024
=> Implement `go install`

Makefile, build/run-test-kind-prow.sh
We pull manifests from each repo, which specifies the `latest` tag. This adds patching logic so that we make sure we're pulling the `latest-<version>` tag.
=> Patch images in Kind

.travis.yml, build/set-claim.sh
- Adds missing `--insecure-skip-tls-verify` flag
- Adds "init" stage for cluster setup
Also moves the conditional `if` to a single build-level configuration.
=> Fix Collective login

build/detect-upstream.sh
for https://github.com/stolostron/governance-policy-propagator/pull/215
=> apply upstream ignorelist to makefile as well

build/patch-dev-images.sh
=> Fix the klusterletaddonconfig pause annotation

test/common/common.go, test/integration/policy_comp_operator_test.go, test/integration/policy_gatekeeper_operator_downstream_test.go, test/integration/policy_gatekeeper_operator_test.go, test/integration/policy_imagemanifest_test.go, test/integration/policy_kyverno_generators_test.go, test/integration/policy_report_metric_test.go
Hopefully addresses the issues found in https://github.com/stolostron/backlog/issues/24061
=> Insights pod missing

test/integration/policy_report_metric_test.go
The insights components are now deployed through this chart:
https://github.com/stolostron/multiclusterhub-operator/tree/release-2.6/pkg/templates/charts/toggle/insights/templates
During that change, some of the labels needed to be updated so that
these tests can get the right resources.
Refs:
- https://github.com/stolostron/backlog/issues/24278
=> Update insights client and metrics selector

build/periodic.sh
=> Update syncing URL

test/common/common.go, test/integration/policy_kyverno_generators_test.go
This should help debug issues such as:
https://github.com/stolostron/backlog/issues/24699
Closes https://github.com/stolostron/backlog/issues/24699
=> Add debug logs when the Kyverno test fails

test/configuration_policy_prune.go
The new test does not check for the Policy on the managed cluster, but
in the future we may implement something to keep that around (possibly
also on the hub) while the ConfigurationPolicy is cleaning up.
Refs:
- https://github.com/stolostron/backlog/issues/24440
=> Implement test for foreground pruning

test/integration/policy_report_metric_test.go
The failures happen inconsistently, and I haven't been able to see them
locally yet.
Refs:
- https://github.com/stolostron/backlog/issues/24827
=> Add additional policyreport debug info on fails

test/common/common.go, test/configuration_policy_prune.go, test/e2e/cert_policy_test.go, test/e2e/configuration_policy_test.go, test/e2e/e2e_suite_test.go, test/e2e/gatekeeper_test.go, test/e2e/hub_templates_encryption_test.go, test/e2e/iam_policy_test.go, test/resources/template-sync-errors/invalid-cr-template.yaml, test/resources/template-sync-errors/pretend-policy-template.yaml, test/template_sync_errors.go
For https://github.com/stolostron/backlog/issues/24750
=> Template error tests

test/common/common.go, test/integration/policy_kyverno_generators_test.go
Relates:
https://github.com/stolostron/backlog/issues/24895
=> Provide the Kubeconfig for Kyverno debug commands

test/integration/policy_zts_cmc_test.go
Signed-off-by: Mahesh Bhoothapuri <mahesh@zettaset.com>
=> Add Test Case For Zts-Cmc Policy

test/integration/policy_zts_cmc_test.go
Addresses:
- https://github.com/stolostron/backlog/issues/25225
=> Add deployment check to ZTS test

test/policy-collection/policy_gatekeeper_operator_downstream_test.go, test/policy-collection/policy_gatekeeper_operator_test.go
This is a manual cherry-pick of #445
=> [release-2.4] Gatekeeper - Delete the created ns to avoid pointless retries

test/integration/policy_comp_operator_test.go
Our E8 and CIS scan policies do have checks for `AGGREGATING` and `DONE`, so it's probably reckless/irresponsible to remove the checks entirely. However, given the length of time it takes for a scan to complete, this PR removes those checks from the BVT so that the scan checks only run on SVT.
~(I'll need to verify that moving these labels works as expected, but I think it should.)~
=> Remove completed compliance scan checks from BVT

test/integration/policy_kyverno_generators_test.go
Addresses:
- https://github.com/stolostron/backlog/issues/25225
=> Patch Kyverno AppSub PlacementRule in policy instead of directly

test/integration/policy_generator_acm_hardening_test.go, test/integration/policy_generator_test.go
Addresses:
- https://github.com/stolostron/backlog/issues/25203
- https://github.com/stolostron/backlog/issues/25410
=> Add logs to cleanup to make failure clearer

test/integration/policy_zts_cmc_test.go
Addresses:
- https://github.com/stolostron/backlog/issues/25429
=> Use managed cluster for ZTS deployment deletion

test/common/user_management.go, test/integration/policy_generator_acm_hardening_test.go
=> Use different user/IDP for hardening tests

test/policy-collection/policy_gatekeeper_operator_downstream_test.go, test/policy-collection/policy_gatekeeper_operator_test.go
This is a manual cherry-pick of https://github.com/stolostron/governance-policy-framework/pull/463
Closes https://github.com/stolostron/backlog/issues/25118
=> [release-2.4] Fix Gatekeeper namespace creation detection

test/integration/policy_gatekeeper_operator_downstream_test.go, test/integration/policy_gatekeeper_operator_test.go
This is a manual cherry-pick of https://github.com/stolostron/governance-policy-framework/pull/463
=> [release-2.5] Fix Gatekeeper namespace creation detection

.github/workflows/e2e.yml, .github/workflows/kind.yml, Makefile
This cherry-picks https://github.com/stolostron/governance-policy-framework/commit/afc15cc16e551796095049fb86df34cdbda00781.
This should help with #471 and cherry-picks a commit from it.
=> Add reusable workflow for running KinD tests

test/performance/performance.go
https://github.com/stolostron/backlog/issues/25463
=> add saturation metrics to config policy performance test

test/common/common.go, test/integration/policy_comp_operator_test.go
A cherry pick attempt failed so manually backported the pr: https://github.com/stolostron/governance-policy-framework/pull/451
Refs:
- https://github.com/stolostron/backlog/issues/25989
=> [release-2.5] Backport compliance operator test fixes manually

.travis.yml
This is to resolve this failure:
https://app.travis-ci.com/github/stolostron/governance-policy-framework/jobs/585004169
=> Install yamllint in the TravisCI environment

.travis.yml
This reverts commit b13fcc2ef167164552a01b43b61c57d776762b76.
Merge pending results of framework runs from:
- #487
=> Revert "Install yamllint in the TravisCI environment"

.ci-operator.yaml, .github/workflows/kind.yml, .travis.yml, Dockerfile.e2etest, go.mod
- https://github.com/stolostron/backlog/issues/26259
=> Bump to Go `v1.19`

test/common/common.go, test/common/policy_utils.go, test/e2e/cert_policy_test.go, test/e2e/configuration_policy_test.go, test/e2e/e2e_suite_test.go, test/e2e/gatekeeper_test.go, test/e2e/hub_templates_encryption_test.go, test/e2e/iam_policy_test.go, test/e2e/policySet_e2e_test.go, test/integration/integration_suite_test.go, test/integration/policy_certificate_test.go, test/integration/policy_comp_operator_test.go, test/integration/policy_etcdencryption_test.go, test/integration/policy_gatekeeper_operator_downstream_test.go, test/integration/policy_gatekeeper_operator_test.go, test/integration/policy_hub_templates_21440_test.go, test/integration/policy_iam_test.go, test/integration/policy_imagemanifest_test.go, test/integration/policy_info_metric_test.go, test/integration/policy_limitmemory_test.go, test/integration/policy_namespace_test.go, test/integration/policy_pod_test.go, test/integration/policy_psp_test.go, test/integration/policy_report_metric_test.go, test/integration/policy_role_test.go, test/integration/policy_rolebinding_test.go, test/integration/policy_scc_test.go, test/integration/policy_set_test.go, test/resources/policy_hub_templates_21440/policy-hub-templates-21440.yaml
Cherry picked commits from #437 with conflicts resolved
=> [release-2.5] common funcs

build/run-e2e-tests-policy-framework.sh
=> Add travis keepalive one-liner to another script

test/common/gitops_utils.go, test/common/user_management.go, test/integration/policy_generator_acm_hardening_test.go, test/integration/policy_generator_test.go
Manual cherry-pick of:
- #497 
- #511
(The Kustomize tests are not included here since that's not available in `2.5`.)
=> [release-2.5] Cherry-pick GitOps utils refactor

test/common/gitops_utils.go, test/common/user_management.go, test/integration/policy_generator_acm_hardening_test.go, test/integration/policy_generator_remote_test.go, test/integration/policy_generator_test.go, test/resources/policy_generator/remote-kustomization/base/kustomization.yaml, test/resources/policy_generator/remote-kustomization/kustomization.yaml, test/resources/policy_generator/remote-kustomization/policyGenerator.yaml, test/resources/policy_generator/subscription-remote.yaml
Manual cherry-pick of:
- #497 
- #511
Addresses:
- https://github.com/stolostron/backlog/issues/25928
=> [release-2.6] Cherry-pick Kustomize generator tests

test/common/policy_utils.go, test/configuration_policy_prune.go, test/integration/policy_kyverno_generators_test.go, test/integration/policy_set_test.go
This backports #514, #516, and #518.
=> Backport Kyverno test fixes

test/policy_ordering.go, test/resources/policy_ordering/dep-plcset-statuscheck.yaml, test/resources/policy_ordering/dep-plcset.yaml, test/resources/policy_ordering/dep-policy-dep-on-plcset.yaml
https://github.com/stolostron/backlog/issues/26190
=> add test for ordering dependent on policy set

test/common/gvr.go, test/integration/policy_generator_acm_hardening_test.go, test/integration/policy_kyverno_generators_test.go
This is a cherry-pick of https://github.com/stolostron/governance-policy-framework/pull/526
=> [release-2.6] Delete the Kyverno subscription on the Hub

test/integration/policy_generator_acm_hardening_test.go, test/resources/policy_generator/acm-hardening_subscription.yaml
Ref:
- https://github.com/stolostron/backlog/issues/26978
=> Update ManagedClusterSetBinding API Version

test/resources/policy_ordering/dep-policy-ignorepending.yaml
ref: https://issues.redhat.com/browse/ACM-2148
=> Fix E2E test for new enum requirement

build/clean-up-cluster.sh, build/patch-cluster.sh
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
=> Replace build-harness `oc/login`

.travis.yml, build/download-clis.sh, build/run-e2e-tests-policy-framework.sh, build/set-claim.sh
This fixes a permission error.
=> Use a local path for the oc CLI in TravisCI

Makefile
https://issues.redhat.com/browse/ACM-3490
=> [release-2.6] Update VERSION_TAG to latest-2.6

Makefile
https://issues.redhat.com/browse/ACM-3490
=> [release-2.7] Update VERSION_TAG to latest-2.7

test/resources/policy_multiline_templatization/policy-multiline-template-hub.yaml, test/resources/policy_multiline_templatization/policy-multiline-template-nohub.yaml
Relates:
https://github.com/stolostron/backlog/issues/27195
=> Ignore default ConfigMaps in multiline template tests

build/periodic.sh
- Drop `2.4`
- Drop `grc-ui`/`grc-ui-api`
- Add policy generator and policy collection
=> CI check script updates

test/common/policy_utils.go, test/integration/policy_comp_operator_test.go, test/integration/policy_gatekeeper_operator_downstream_test.go
Generalizes code in `EnforcePolicy` to create and utilize a new `InformPolicy` function
=> Add `setRemediationAction`

test/common/policy_utils.go, test/e2e/configuration_policy_test.go
for https://github.com/stolostron/config-policy-controller/pull/434
=> Add more temporary logs to debug failures

.github/workflows/repo-config.yml, .gitignore, Makefile, build/codebase-check.sh, build/common.sh, build/common/Makefile.common.mk, build/common/config/.golangci.yml, build/install-dependencies.sh, build/periodic.sh
Initial common Makefile, including:
- Dependency installations
- Controller service account for running E2E tests.
Add code health check action:
- Add script to check for common Makefile
- Migrate CRD check to new script from periodic.sh
- Add GitHub Action to run both scripts and post to Slack
ref: https://issues.redhat.com/browse/ACM-3321
=> Initialize a more commoner Makefile

test/configuration_policy_prune.go
=> Specify prune test timeout

test/configuration_policy_prune.go
=> Bump prune deletion timeout

test/configuration_policy_prune.go
The prune test is failing because the controller fails to update the status and then isn't aware that it created the object on the next reconcile. This should at least make this E2E failure clearer.
=> Add check for `createdByPolicy`

test/integration/policy_multiline_templatization_test.go
The userNamespace needed to be created on the managed cluster for this test, and the target ConfigMap namespace needed to be created on the hub. This also adjusts the cleanup accordingly.
ref: https://github.com/stolostron/backlog/issues/27232
=> Fix the multiline test

test/integration/policy_multiline_templatization_test.go
The userNamespace needed to be created on the managed cluster for this test, and the target ConfigMap namespace needed to be created on the hub.
ref: https://github.com/stolostron/backlog/issues/27232
=> Cherry pick to 2.7: Fix the multiline test

Makefile, build/common/Makefile.common.mk, test/integration/policy_comp_operator_test.go, test/integration/policy_gatekeeper_operator_downstream_test.go, test/integration/policy_info_metric_test.go, test/integration/policy_report_metric_test.go
- Move OLM install script to `./bin` (because it's weird seeing a generic "install.sh" file at the root of the repo)
- Update `gosec` command in common Makefile
=> Makefile updates

build/codebase-check.sh, build/common.sh
I missed a path update after migrating the `policy-grc-squad`
Followup to:
- #610
=> Set directory for repo.txt

test/integration/policy_kyverno_generators_test.go
Kyverno v1.10.0 introduced breaking changes to separate it into separate deployments
ref: https://github.com/kyverno/kyverno/releases/tag/v1.10.0
=> Fix Kyverno deployment name check

test/e2e/configuration_policy_test.go
Relates:
https://issues.redhat.com/browse/ACM-5175
=> Update the policy history to match the new status message format

test/common/policy_utils.go, test/integration/policy_gatekeeper_operator_downstream_test.go
ref: https://github.com/stolostron/backlog/issues/27336
=> Lengthen time to check for managed cluster policy

Makefile
Some labels had not been updated to match current labeling. The Hub cluster had also been missed for log collection. Both of these can make E2E/canary triaging a bit more straightforward.
=> Fix ACM debug collection

Makefile, test/common/policy_utils.go, test/integration/policy_gatekeeper_operator_downstream_test.go
Manual cherry pick of:
- #636 
- #635
=> [release-2.7] Manual cherry-pick of E2E fixes

Makefile
Our Travis CI test has an issue after adding a webhook in the propagator controller. The solution is `make webhook ` should be ahead of deploying `operator.yaml `
=> Add webhook before propagator controller install in travis

Makefile, test/common/policy_utils.go, test/integration/policy_gatekeeper_operator_downstream_test.go
Manual cherry pick of:
- #636 
- #635
=> [release-2.6] Manual cherry-pick of E2E fixes

test/e2e/hub_templates_encryption_test.go
This also changes the comparison to use native Gomega assertions.
Relates:
https://issues.redhat.com/browse/ACM-4873
=> Move flaky test check to an eventually

test/e2e/hub_templates_encryption_test.go
I have no idea whether this will do anything, but it might... 🤷‍♂️ 
ref: https://issues.redhat.com/browse/ACM-4873
=> Adjust encryption test to use new variable

.github/workflows/kind.yml, test/e2e/hub_templates_encryption_test.go
- Fixes an E2E report filename
- Also reverts this PR since it's not necessary:
- #660
=> Fix report file name

Makefile, build/common/Makefile.common.mk, test/integration/policy_comp_operator_test.go, test/integration/policy_gatekeeper_operator_downstream_test.go, test/integration/policy_info_metric_test.go, test/integration/policy_report_metric_test.go
- Move OLM install script to `./bin`
- Update `gosec` command in common Makefile
- E2E assertion updates
=> Makefile updates; E2E assertion updates

.github/workflows/kind.yml, Makefile
See each commit for more details.
=> Fix the framework debug workflow

.github/workflows/repo-config.yml, build/codebase-check.sh, build/periodic.sh
Before I had concerns about the volume of information, but seeing the integration test output combined with the reduced output here it's time to go ahead and output the information to Slack directly.
=> Output CI results to Slack

test/resources/policy_generator/acm-hardening_subscription.yaml, test/resources/policy_generator/subscription-remote.yaml, test/resources/policy_generator/subscription.yaml
I forgot to update the `placementRef` in the Subscription 🤦‍♂️ 
Followup to:
- #681
=> Fix E2E PlacementRef in Subscriptions

build/common.sh, build/detect-modules.sh, build/main-branch-sync/repo.txt, build/main-branch-sync/update-owners.sh
Add `2.10`, drop `2.6`, drop `*-sync` repos
=> Update versions checked in scripts

.github/workflows/integration.yml, build/main-branch-sync/sync.sh
I don't actually know whether this will allow us to also push, but it's worth a shot? 😄
=> Pass token to the fast-forward script

build/main-branch-sync/sync.sh
=> Fix git URL in sync.sh

build/main-branch-sync/sync.sh
=> Fix fast-forward branch variable

Makefile, test/integration/policy_info_metric_test.go, test/integration/policy_report_metric_test.go, test/resources/policy_generator/subscription-remote.yaml, test/resources/policy_generator/subscription.yaml
Selective cherry-pick of:
- #681
- #682
- #683
Specifically, this PR:
- Removes allowList from appsub
- Adds ManagedClusterSetBindings to generator appsub
ref:
- https://github.com/stolostron/backlog/issues/27443
- https://github.com/stolostron/backlog/issues/27444
=> [release-2.9] Update integration tests for Placement

build/main-branch-sync/rotate-secrets.sh
- Removing unused Prow Kind credentials
- Adding gatekeeper-operator token
Connected with:
- https://github.com/stolostron/gatekeeper-operator/pull/52
=> Update secret rotation script

test/integration/policy_diff_generation_test.go, test/resources/diff_generation/diff_generation.yaml
ref: https://issues.redhat.com/browse/ACM-9072 (Dev issue)
ref: https://issues.redhat.com/browse/ACM-9074 (QE issue)
=> Add integration tests for diff logging

.ci-operator.yaml, Dockerfile.e2etest, go.mod, go.sum
ref: https://issues.redhat.com/browse/ACM-9734
=> [release-2.9] Update to Go v1.21

.ci-operator.yaml, Dockerfile.e2etest, go.mod, go.sum
ref: https://issues.redhat.com/browse/ACM-9734
=> [release-2.7] Update to Go v1.21

build/common/Makefile.common.mk
Sync changes from:
- https://github.com/open-cluster-management-io/governance-policy-propagator/pull/177
=> Sync common Makefile

test/integration/policy_info_metric_test.go
The label is no longer unique with the compliance history API coming on board, and I don't think there's much risk of the name being changed.
ref: https://github.com/stolostron/backlog/issues/27486
=> Identify the metrics svc/route by name

Makefile
=> Hardcode kubeconfig filenames

build/README.md, build/pull-requests.sh
Example output:
```
##################################################
##################################################
TITLE                                               USER               DATE        URL
Add `go-update.sh`                                  dhaiducek          2023-08-09  github.com/stolostron/governance-policy-framework/pull/655
Implement `Rollouthandler`                          dhaiducek          2023-08-18  github.com/open-cluster-management-io/governance-policy-propagator/pull/125
[99][sig-policy] PolicySet rollout                  dhaiducek          2023-10-02  github.com/open-cluster-management-io/enhancements/pull/103
Add default exempting namesapces to the config ...  yiraeChristineKim  2023-11-14  github.com/stolostron/gatekeeper-operator/pull/27
Move …
```
=> Add a script for finding PRs from the squad

test/e2e/cert_policy_test.go
Related to https://github.com/stolostron/cert-policy-controller/pull/250/
=> Change cert-policy history message

test/common/gvr.go, test/common/policy_utils.go, test/integration/policy_install_operator_test.go, test/resources/policy_install_operator/operator_policy_no_group.yaml, test/resources/policy_install_operator/operator_policy_with_group.yaml
ref: https://issues.redhat.com/browse/ACM-9894
=> Add tests for installing a specific operator via OperatorPolicy

.github/workflows/repo-config.yml, build/pull-requests.sh
- The code health summary was incorrectly referring to a variable that didn't exist. Since it's collapsed anyway, this updates it to print out the full unabridged report.
- Also adds `https` to the PR report so Slack parses the URL properly (and shortens some columns a bit)
=> Script fixes

test/integration/policy_install_operator_test.go
ref: https://issues.redhat.com/browse/ACM-6652
=> Increase operator install test timeout value for checking the CSV

test/integration/compliance_history_test.go, test/resources/compliance_history/policy-gk.yaml, test/resources/compliance_history/policy-install-gk.yaml, test/resources/compliance_history/policy-uninstall-gk.yaml, test/resources/compliance_history/policy.yaml
Relates:
https://issues.redhat.com/browse/ACM-10033
=> Add a BVT test for compliance history with Gatekeeper integration

test/integration/policy_install_operator_test.go
=> Fix OperatorPolicy cleanup commands

test/integration/compliance_history_test.go, test/resources/compliance_history/cert-policy.yaml, test/resources/compliance_history/operator-policy-invalid.yaml
Ref: https://issues.redhat.com/browse/ACM-10146
=> Add operator and cert policy event test

test/integration/policy_install_operator_test.go
- Check the message before compliance (since that test failure could be more helpful)
- Fetch the CSV name dynamically (since a static version could be flaky if a new z-stream is released)
- Only attempt an OperatorGroup/CSV deletion if a name was discovered
- Clean up all CSV when deployed clusterwide (this is mainly for the benefit of the Canaries)
Followup to:
- #743 
- #736
=> OperatorPolicy test fixes

test/integration/operator_policy_error_test.go, test/resources/operator_policy/test-op-err-correct.yaml, test/resources/operator_policy/test-op-err-initial.yaml
ref: https://issues.redhat.com/browse/ACM-9895
=> Add BVT tests for operator policy errors

Makefile
ref: https://issues.redhat.com/browse/ACM-4811
=> Fix broken URLs in Makefile

Makefile
ref: https://issues.redhat.com/browse/ACM-4811
=> Fix more broken URLs in Makefile

test/resources/hosted_mode/managed-cluster-addon.yaml
imageOverride should be `governance_policy_framework_addon` key
=> Fix governance_policy_framework_addon imageOverrides

.github/workflows/kind.yml, Makefile
ref: https://issues.redhat.com/browse/ACM-4811
=> Conditionally skip iam and cert policy tests

Makefile
ref: https://issues.redhat.com/browse/ACM-4811
=> Fix TEST_ARGS variable reference

test/integration/compliance_history_test.go, test/resources/compliance_history/policy-uninstall-gk.yaml
The subscription should be deleted prior to the CSV.
Followup to:
- #759
=> Swap uninstall Gk dependencies

test/integration/policy_install_operator_test.go
cherry-pick refs:
- https://github.com/stolostron/governance-policy-framework/pull/741
- https://github.com/stolostron/governance-policy-framework/pull/743
- https://github.com/stolostron/governance-policy-framework/pull/746
=> [Manual Sync release-2.10] OperatorPolicy BVT test fixes

test/integration/compliance_history_test.go
non-clean **delete-gatekeeper-policy** affects other policies and re-tests, clusters.
=> Clean gatekeeper-uninstall-policy after the test

test/integration/operator_policy_error_test.go, test/resources/operator_policy/test-op-err-correct.yaml, test/resources/operator_policy/test-op-err-initial.yaml
ref: https://issues.redhat.com/browse/ACM-9895
=> [Release-2.10] Cherry pick of BVT tests for operator policy errors

test/integration/compliance_history_test.go, test/resources/compliance_history/policy-gk-prereq.yaml, test/resources/compliance_history/policy-gk-prereq2.yaml, test/resources/compliance_history/policy-gk.yaml
The test didn't account for multiple clusters.
=> Fix the compliance history test for Gatekeeper integration

.github/workflows/repo-config.yml
Runs `clusteradm` to deploy the policy framework on OCM and does basic checks to see whether the addons are available.
Sample run: https://github.com/dhaiducek/governance-policy-framework/actions/runs/8459324246/job/23175431403
=> Add `clusteradm` to periodic CI

test/integration/policy_iam_test.go
ClusterRoleBinding didn't clean up well. Therefore this PR will fix the issue.
Ref: https://issues.redhat.com/browse/ACM-10793
=> Delete clusterRoleBinding in the policy iam test

test/integration/compliance_history_test.go, test/resources/compliance_history/cert-policy.yaml, test/resources/compliance_history/cert-prereq.yaml, test/resources/compliance_history/operator-policy-invalid.yaml, test/resources/compliance_history/operator-prereq.yaml
Fix this https://redhat-internal.slack.com/archives/CVAB9H3DE/p1711973234038419
=> Fix cert and operator policy in compliance history

test/integration/compliance_history_test.go, test/integration/policy_install_operator_test.go
- Fix the policy status flaky issue in the operator install test
- Fix event length issue in the certification compliance history
=> Hotfix cert install hotfix

test/integration/compliance_history_test.go
Relates:
https://github.com/stolostron/backlog/issues/27551
=> Add more details to Gatekeeper compliance history failures

test/integration/compliance_history_test.go
This was added to the compliance message in
https://github.com/open-cluster-management-io/config-policy-controller/pull/222
=> Add CRD to operator-policy message

test/integration/compliance_history_test.go, test/resources/compliance_history/cert-prereq.yaml
This will fix https://redhat-internal.slack.com/archives/CVAB9H3DE/p1712678150872979 issue
=> Change the adding cert secret from command to policy

build/codebase-check.sh
That way, we have a signal that it needs to be updated.
=> Add check for framework `release-X.Y` branch in Prow

test/common/policy_utils.go, test/integration/compliance_history_test.go, test/integration/policy_install_operator_test.go
This is a manual cherry-pick of https://github.com/stolostron/governance-policy-framework/pull/788
/assign @mprahl
=> [release-2.10] Add some debug messages and address some flaky tests

build/run-e2e-tests-policy-framework-prow.sh
ref:
- https://issues.redhat.com/browse/ACM-11162
- https://github.com/openshift/release/pull/51057
=> Set hub kubeconfig for patch script

test/integration/integration_suite_test.go
=> Use the release-2.8 branch for the policy-collection

test/integration/integration_suite_test.go
=> Use the release-2.10 branch for the policy-collection

test/integration/integration_suite_test.go
=> Use the release-2.7 branch for the policy-collection

test/integration/integration_suite_test.go
=> Use the release-2.9 branch for the policy-collection

.github/workflows/repo-config.yml, build/import-managed.sh
`jsonpath` wasn't working (I think perhaps because the CLI in the CI is older), but this looks cleaner anyway.
=> Simplify wait commands

test/integration/policy_comp_operator_test.go, test/integration/policy_gatekeeper_operator_downstream_test.go
Some cleanup commands were failing because the test hadn't run to completion.
ref: https://github.com/stolostron/backlog/issues/27595
=> Polish cleanup nodes

test/integration/policy_diff_generation_test.go
The diff output was expanded.
ref: https://issues.redhat.com/browse/ACM-11421
=> Update diff integration test

test/integration/compliance_history_test.go
Relates:
https://issues.redhat.com/browse/ACM-11847
=> Unset the CMA defaultConfig after the test run

Makefile
Relates:
https://issues.redhat.com/browse/ACM-11952
=> Install the OperatorPolicy CRD on kind environment

test/integration/recreate_option_test.go, test/resources/recreate_option/policy-configmap.yaml, test/resources/recreate_option/policy-initial-deployment.yaml, test/resources/recreate_option/policy-update-deployment.yaml
Relates:
https://issues.redhat.com/browse/ACM-11874
=> Add a BVT test for ConfigurationPolicy recreateOption

build/periodic-slack-report.sh
Getting the CURRENT_VERSION is based on what's in the main-branch-sync script.
=> Specify fast-forward branch in slack report

build/periodic.sh
`release-2.12` doesn't exist yet.
=> Skip checking missing `pipeline` branch

README.md, build/branch-create/repo.txt, build/branch-create/update-release.sh, build/common.sh, build/periodic.sh
- Remove references to grc-ui
- Consolidate the release update into a single PR
- Add the `git-fast-forward` step that must-gather uses
- Add `must-gather` to CI checks
ref: https://issues.redhat.com/browse/ACM-12429
=> Add `must-gather` to release flows

README.md
Resolve detected CI failure:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/branch-ci-stolostron-governance-policy-framework-release-2.11-images/1803073697800523776
=> [release-2.11] Build refresh

build/main-branch-sync/refresh.sh
If the date was missing, the script was erroring and not continuing.
=> Update refresh script to add missing date

test/e2e/hub_templates_encryption_test.go
Getting hub encryption test results is slow when it is in hosted mode. This PR will solve the problem.
I tested over 5 times. No issues anymore.
Ref: https://issues.redhat.com/browse/ACM-11497
=> Add debug logs for hub encryption flaky issue

build/main-branch-sync/rotate-secrets.sh
Some details were slightly unclear to a first-timer (me).
=> Add some notes to the rotation script

test/e2e/hub_templates_encryption_test.go
Add policy-framework-addon logs and configuration yaml output for debug
=> Add policy-framework-addon logs and configuration yaml output for debug

test/performance/performance.go
This metric is no longer part of config-policy-controller since it became event driven.
=> Remove the saturation metrics data from performance test script

test/integration/operator_policy_complianceconfig_test.go, test/resources/operator_policy/test-op-complianceconfig-1-modified.yaml, test/resources/operator_policy/test-op-complianceconfig-1.yaml, test/resources/operator_policy/test-op-complianceconfig-modified.yaml, test/resources/operator_policy/test-op-complianceconfig.yaml
This commit tests the ability of complianceConfig to configure compliance in specific situations.
Ref: https://issues.redhat.com/browse/ACM-11661
=> Add BVTs for complianceConfig

test/performance/performance.go, test/performance/resources/setup/metrics-configmap.yaml
=> Collect memory in the performance script

.ci-operator.yaml, build/Dockerfile.e2etest, go.mod
=> [release-2.11] Update to Go v1.22

go.mod
=> [release-2.11] Update to Go 1.22

.ci-operator.yaml, build/Dockerfile.e2etest, go.mod
=> [release-2.10] Update to Go v1.22

.ci-operator.yaml, Dockerfile.e2etest, go.mod
=> [release-2.9] Update to Go v1.22

.ci-operator.yaml, Dockerfile.e2etest, go.mod
=> [release-2.8] Update to Go v1.22

.ci-operator.yaml, build/Dockerfile.e2etest, go.mod
=> Update to Go v1.22

build/branch-create/README.md, build/branch-create/update-release.sh
- Add check that base commit is up-to-date
- Address some shellcheck issues
- Replace version in Konflux job
- Add virtual environment for Python
=> Update Prow update script

.github/workflows/integration.yml, .github/workflows/repo-config.yml
Followup to:
- #889 
ref: https://github.com/slackapi/slack-github-action/tree/main?tab=readme-ov-file#technique-3-slack-incoming-webhook
=> Fix Slack posting

build/main-branch-sync/update-owners.sh
- Make paths relative to the script
- Add upstream repos
- Add logic for when there are multiple OWNERS files in a repo
=> Fix owners update script

.github/workflows/sonarcloud.yml
ref: https://sonarsource.atlassian.net/browse/SCSCANGHA-28
=> Update Sonarcloud action

README.md
=> [release-2.12] Build refresh

test/integration/policy_message_test.go, test/resources/policy_message/namespace-selector-prereq.yaml, test/resources/policy_message/obj-selector-prereq.yaml, test/resources/policy_message/policy-message-namespace-selector.yaml, test/resources/policy_message/policy-message-obj-selector.yaml
- All Integration tests passed
Ref: https://issues.redhat.com/browse/ACM-15801
=> Add tests for consolidated messages to SVT

test/integration/policy_hub_templates_21440_test.go, test/integration/policy_multiline_templatization_test.go, test/integration/policy_selector_test.go, test/resources/policy_selector/policy-selector.yaml
ref: https://issues.redhat.com/browse/ACM-15811
=> Add an `objectSelector` integration test

build/common/Makefile.common.mk, build/common/config/.golangci.yml, go.mod, test/common/common.go, test/common/metrics.go, test/common/policy_utils.go, test/common/user_management.go, test/configuration_policy_prune.go, test/integration/policy_comp_operator_test.go, test/integration/policy_generator_acm_hardening_test.go, test/integration/policy_report_metric_test.go, test/performance/performance.go, test/policy_ordering.go
Ref: https://issues.redhat.com/browse/ACM-8341
=> Upgrade golangci-lint to v1.64.8

.ci-operator.yaml, .github/workflows/kind.yml, build/Dockerfile.e2etest, build/common/Makefile.common.mk, go.mod, go.sum
=> [release-2.13] Address `oauth2` vuln

.ci-operator.yaml, .github/workflows/kind.yml, build/Dockerfile.e2etest, build/common/Makefile.common.mk, go.mod, go.sum
=> [release-2.12] Address `oauth2` vuln

.ci-operator.yaml, build/Dockerfile.e2etest, go.mod, go.sum
=> Address `oauth2` vuln

build/main-branch-sync/repo-extra.txt, build/main-branch-sync/update-owners.sh
- Fixes Shellcheck errors
- Adds logic to iterate over release branches
- Adds logic to detect upstream repos and skip the main branch for stolostron
- Uses the `gh` CLI to open PRs
=> Update the owners file script
