- .travis.yml
- build/run-e2e-tests.sh
Due to E2E test concurrency, we've implemented a `CYPRESS_STANDALONE_TESTSUITE_EXECUTION` flag so that the UI E2E tests loosen its checks due to the extra policies that are present from the other E2E tests.
GRC UI PR: https://github.com/open-cluster-management/grc-ui/pull/498
> Disable standalone UI tests

- .travis.yml
- build/run-e2e-tests-ui.sh
Implement `STANDALONE_TESTSUITE_EXECUTION` properly (reverts https://github.com/open-cluster-management/governance-policy-framework/pull/78)
(See related PR https://github.com/open-cluster-management/grc-ui/pull/502)
> Move standalone var to Docker call

- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
I think this would be the proposed change to address the failing canary.  https://github.com/open-cluster-management/backlog/issues/10545
@ycao56 What do you think about the canary failure and whether you think this will help?
> increase timeout for gatekeeper pod to be running

- test/policy-collection/policy_comp_operator_test.go
for https://github.com/open-cluster-management/backlog/issues/12138
avoid checking for error inside this eventually() block to allow the test to retry after a failure
> remove error check inside eventually() for ComplianceCheckResult

- test/policy-collection/policy_gatekeeper_operator_test.go
To match the (pending) PR changing where the community gatekeeper
operator is installed, because `openshift-*` namespaces might be
restricted in some OpenShift clusters.
Refs:
- https://github.com/open-cluster-management/policy-collection/pull/125
- https://github.com/open-cluster-management/backlog/issues/13759
> Move community operator to unrestricted namespace

- test/policy-collection/policy_comp_operator_test.go
- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
A configuration policy cannot create the `openshift-compliance` namespace on ROSA clusters because `openshift-*` namespaces are restricted to "non-customer" workloads. Since that is the correct namespace for the operator, we will just skip those tests on clusters with this situation.
This also includes a fix for https://github.com/open-cluster-management/governance-policy-framework/pull/114, because I forgot to update the gatekeeper namespace again after changing it in the policy. It is now `gatekeeper-system`.
Update:
After getting my hands on a ROSA cluster to test the policies more throughly, I found that the upstream operator can install correctly with these namespace changes, but it won't function correctly because it would still need to create the `openshift-gatekeeper-system` …
> Skip compliance operator tests on ROSA

- test/policy-collection/policy_comp_operator_test.go
The sample gatekeeper policy created during the tests makes an admission
webhook that prevents the server-side dry-run from testing whether an
openshift-* namespace can be created. But if gatekeeper (and this rule)
are already present, then we can assume we would be able to make the ns.
Refs:
- https://github.com/open-cluster-management/backlog/issues/13759
> Add case to not skip gatekeeper tests

- test/policy-collection/policy_comp_operator_test.go
To me it seems like we should just check for an error instead of ignore the error.
The goal of this change is to fix the failure identified in issue https://github.com/open-cluster-management/backlog/issues/14258
> check for an error instead of ignoring it

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Makefile
- README.md
- doc/development.md
- test/policy-collection/policy_collection_suite_test.go
- Adds `TEST_FILE` flag for running individual test files
- Adds a file `doc/development.md` to document how to run tests locally
- Update the open source files to comply with open source requirements
> Enhance and document local test runs

- test/e2e/gatekeeper_test.go
- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
The root cause of many of the gatekeeper test failures in the canaries and these e2e tests seems to be from updates to the gatekeeper operator / gatekeeper itself. The changes here should cover old and new cases, since the version of the operator, and the version of gatekeeper the operator installs, may depend on the version of the openshift cluster.
> Gatekeeper e2e failures

- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
Previously the name was gatekeeper-operator-controller-manager-xxx, but
in newer versions it might just be gatekeeper-operator-controller-xxx.
Because of the nature of this change, the test will check for the pod
regardless of which version was installed.
> Update community gatekeeper controller name

- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
In https://github.com/open-cluster-management/governance-policy-framework/pull/127, I meant to update in the *upstream* tests, but mistakenly only added it to the *downstream* tests. Looks like this is still the only e2e test failure at this point.
> Upstream gk ctrl name

- test/e2e/gatekeeper_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
The changes to these tests should allow them to function correctly for
both the "old" and "new" versions of the gatekeeper and operator. Those
projects adjusted some details in their deployments and messages.
Refs:
- https://github.com/open-cluster-management/backlog/issues/14914
This PR also updates the release-2.3 branch tests / make targets to use the `latest-2.3` images.
> [release-2.2] Backport gatekeeper test updates

- .travis.yml
Old branches were not publishing their test image, which meant that the canaries couldn't pull the updated image. One Slack thread about this: https://coreos.slack.com/archives/C01KV8QDATA/p1628803129010600
We hadn't previously run into this because it looks like we hadn't had to backport any changes here until the gatekeeper problems.
> 2.3-publish-fix

- .travis.yml
Old branches were not publishing their test image, which meant that the canaries couldn't pull the updated image. One Slack thread about this: https://coreos.slack.com/archives/C01KV8QDATA/p1628803129010600
We hadn't previously run into this because it looks like we hadn't had to backport any changes here until the gatekeeper problems.
> [release-2.2] Fix publishing old images

- test/common/common.go
- test/common/gvr.go
- test/e2e/cert_policy_test.go
- test/e2e/configuration_policy_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/gatekeeper_test.go
- test/e2e/iam_policy_test.go
- test/policy-collection/policy_collection_suite_test.go
- test/policy-collection/policy_comp_operator_test.go
- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
One interesting detail here is that the command line flags are parsed
by ginkgo at some unknown time. So the `clientHub` can't be defined in
the `common` package, or it would only ever use the default kubeconfig
settings.
> Move common test setup to separate package

- test/common/common.go
- test/policy-collection/policy_comp_operator_test.go
- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
- test/policy-collection/policy_iam_test.go
- test/resources/iam_policy/clusterrolebinding.yaml
- test/resources/iam_policy/group.yaml
This canary test is added in addition to the existing E2E tests in order to
test that RHBZ#1981127 is resolved. This must be done as a canary
test since it queries for OpenShift group memberships and this is not
supported on other Kubernetes distributions.
Related to:
https://github.com/open-cluster-management/backlog/issues/14166
> Add a canary test for the IAM policy limitclusteradmin

- build/run-test-image.sh
- test/common/common.go
- test/common/gvr.go
- test/integration/integration_suite_test.go
- test/integration/policy_info_metric_test.go
- test/resources/policy_info_metric/compliant.yaml
- test/resources/policy_info_metric/noncompliant.yaml
The tests in the propagator itself verifies some of these same things,
but the tests here use the service and rbac-proxy set up in the Helm
chart, to verify they are working as expected. One additional test is
to verify that the metrics can't be seen by unauthorized users.
This utilizes the `oc` cli's ability to expose services as a route, so
that we can curl directly to the metrics endpoint. One alternative that
I considered was using a port-forward, but that was difficult to manage.
Refs:
- https://github.com/open-cluster-management/backlog/issues/14992
> Add metrics tests to run on canaries

- test/integration/policy_info_metric_test.go
The `io.ReadAll` function was added in Go version 1.16, so depending
on the version used by test runners, the tests might fail to compile.
The `ioutil.ReadAll` function still exists and can be used for
compatability.
Since Go 1.17 just came out, we will need to bump up versions in our go.mod and test runners (we currently use 1.14), but that is a separate issue. This will fix the e2e tests with minimal changes.
> Use ioutil.ReadAll instead of io.ReadAll

- build/run-test-image.sh
It is failing on the e2e clusters, partly because some of the tests are
not using the right kubeconfig, but also because the e2e clusters do not
use the updated deployment with the rbac proxy and service endpoint that
this suite would test.
> Disable new metrics test

- test/integration/policy_info_metric_test.go
- test/policy-collection/policy_iam_test.go
This is required by the CICD team. See the following comment for
context:
https://github.com/open-cluster-management/backlog/issues/15560#issuecomment-911875009
> Add metadata for the canary tests to be identifed by CICD

- test/policy-collection/policy_comp_operator_test.go
Not sure if this will fix it, but I'm hoping so. I watched the compliance operator pods during a run, and they all seemed to come up okay.
```
$ oc get pods -n openshift-compliance
NAME                                                              READY   STATUS     RESTARTS   AGE
compliance-operator-8c9bc7466-pxkmc                               1/1     Running    1          4m7s
ocp4-e8-api-checks-pod                                            0/2     Init:0/2   0          2s
ocp4-e8-rs-7b5f58f497-zrg92                                       0/1     Pending    0          2s
ocp4-openshift-compliance-pp-6d7c7db4bd-nx679                     1/1     Running    0          98s
rhcos4-e8-master-ip-10-0-132-93.us-east-2.compute.internal-pod    0/2     Init:0/1   0          2s …
```
> Increase compliance operator pod timeout

- build/run-test-image.sh
They were working on the grc e2e cluster / periodic tests, but failing
in the canary. The `oc whoami -t` command seems to fail in that env,
but that token is needed for auth with the metrics rbac proxy.
> Disable metrics tests from canaries

- Makefile
- doc/development.md
- test/common/common.go
- test/integration/policy_info_metric_test.go
The secret name had single quotes (`'`) around it, (I think) causing subsequent commands to fail. This removes the quotes and also adds logic to not print any output from secrets (though maybe this is too broad).
> Fix token fetch

- Dockerfile.e2etest
Errors:
- `go.mod file not found`
- `"gcc": executable file not found`
> Fix build errors

- Dockerfile.e2etest
The golang image is susceptible to hitting Docker rate limiting, so the CICD image is a better option long-term
> Update builder image

- test/integration/policy_report_metric_test.go
canary failures seem to be because the poll interval change isn't being applied quickly enough so the metric takes longer than expected to show up
> increase timeout for metric availability

- build/run-test-image.sh
I noticed if the policy-collection test suite has failures, the integration test suite would be skipped. see https://app.travis-ci.com/github/open-cluster-management/governance-policy-framework/jobs/539861128#L2447
This might help.
> merge two test suites into single ginkgo run

- test/integration/policy_generator_test.go
It seems that sometimes logging in as the new user isn't ready after the
current timeout. Occasionally, it'll fail with a 401 HTTP status code.
This doubles that timeout in the hopes of making this test more stable.
Here is an example of a passing and failing canary run:
https://app.travis-ci.com/github/open-cluster-management/canary/jobs/539930135
https://app.travis-ci.com/github/open-cluster-management/canary/jobs/539991005
> Increase a timeout in the policy generator test

- test/integration/policy_generator_test.go
This sets the timeout to five minutes from two minutes. Locally, against
an OCP cluster, this usually takes about 15 seconds, but on some
clusters, this can take longer.
In essence, we are waiting for the cluster authentication operator to
notice the IDP configuration change and modify the oauth-openshift
deployment in order to restart the pods.
> Increase the timeout for the login in the policy generator test

- test/policy-collection/policy_iam_test.go
Canary failure: https://github.com/open-cluster-management/backlog/issues/16600
GRC integration test failure: https://app.travis-ci.com/github/open-cluster-management/governance-policy-framework/jobs/540596633#L2473-L2477
Still need to figure out the long term solution for test collision. 
Increasing the time out for now to wait for the iam policy test from GRC-UI to complete. iam policy test from GRC-UI takes around 5 minutes to complete. see https://app.travis-ci.com/github/open-cluster-management/canary/jobs/540539004#L839
Once completed, it should clean up the clusterrolebinding thus this test should pass.
> increase time out to 5 mins

- Makefile
- build/run-test-kind-prow.sh
- `GOPATH` wasn't set in the EC2 instance, so this adds that logic to the Makefile
- Go refuses to honor a `go.mod` file in `/tmp`, so this moves work to a subdirectory
> Fix kind prow

- test/e2e/gatekeeper_test.go
This should address the flakiness of gatekeeper e2e test for grc pipeline
https://app.travis-ci.com/github/open-cluster-management/governance-policy-framework/builds/239542715
> Increase time out for gatekeeper admission

- test/integration/policy_report_metric_test.go
https://github.com/open-cluster-management/backlog/issues/17450
logs for the configurationpolicy controller for this test showed
```
{"level":"error","ts":1634762888.972851,"logger":"configuration-policy-controller","msg":"Operation cannot be fulfilled on configurationpolicies.policy.open-cluster-management.io \"policyreport-metric-noncompliant-policy-ns\": the object has been modified; please apply your changes to the latest version and try again","error":"Operation cannot be fulfilled on configurationpolicies.policy.open-cluster-management.io \"policyreport-metric-noncompliant-policy-ns\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t …
```
> double policy timeout in policyreport test

- .travis.yml
In order to collect more test summary information, we might want to use
a webhook, as opposed to relying on messages sent through slack. At the
very least, I want to know what information is exactly in the webhook
that we might be able to use.
The endpoint is encrypted, so it doesn't get flooded or anything.
Refs:
- https://github.com/open-cluster-management/backlog/issues/17431
> Send travis notifications to a webhook

- test/policy-collection/policy_comp_operator_test.go
- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
These were occasionally causing test failures when the cluster was just
a little bit slow. This increases the timeouts for these checks to a
consistent 120 seconds (these were only 60 before, but some others were
already 120).
Refs:
- https://github.com/open-cluster-management/backlog/issues/18003
> Increase timeouts while checking for running pods

- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
It worked locally, but it looks like this is needed in the test run.
Followup to:
- #217 
Signed-off-by: Dale Haiducek <dhaiduce@redhat.com>
> Specify kubeconfig in dryrun patch

- build/periodic.sh
There's a desire to know when prow jobs fail on our release branches
since publishes to those branches happens automatically and failures
generally do not grab our attention.  This script can help and could
send slack messages through the prow framework which only allows
slack messages on periodic jobs -- not our existing post submit jobs.
Refs:
- https://github.com/open-cluster-management/backlog/issues/17925
> Periodic job that can be run to detect prow publish failures

- build/periodic.sh
Switch one of the git clones from using ssh to https.  The ssh style
of doing a clone doesn't work in prow.
> There's a problem with doing the git clones from prow

- build/periodic.sh
Enhance the experience so error message "may" appear in the prow log
summary without having to drill into the raw log details.  Dale
saw the prow error checking looks for `ERROR` so using that value
instead of `WARNING` in the message.
Refs:
- https://github.com/stolostron/backlog/issues/17925
> Prow may match our errors better using ERROR instead of WARNING

- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
This should avoid gatekeeper breaking other test cases in canary https://github.com/stolostron/backlog/issues/19926
> Use namespaceSelector to restrict gatekeeper to only perform in policy-test namespace

- test/policy-collection/policy_comp_operator_test.go
Testcases were skipped due to addon framework change
> Re-enable Gatekeeper upstream test

- .gitignore
- build/periodic.sh
- Makes `git` output quiet to minimize irrelevant logs
- Adds scanning for all repos (originally some repos were omitted since they didn't have image builds or images didn't match)
- Adds support for differently named and multiple images (i.e. `grc-ui`/`grc-ui-tests` and `grc-policy-framework-tests`)
- Adds file that only contains errors
- Dumps final log at the end, cleaning up duplicate lines and dumping it all at the end of the script for simplicity when looking through Prow output, for example:
```
****
PROW STATUS REPORT:
****
ERROR: Prow job failure: config-policy-controller 2.5
Link: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stolostron-config-policy-controller-release-2.5-publish/1499488879722369024
Link: …
```
> Enhance Prow checking script

- test/common/user_management.go
- test/integration/policy_generator_test.go
The BVT tests started failing recently with the error
"error when retrieving current configuration of..." in the Policy
Generator test. This is due to the user not having read access in
the namespace that the subscription is getting created in.
It's unclear why this is failing now because the created
subscription-admin user has the
open-cluster-management:subscription-admin role, which grants this
access.
This test now no longer relies on the subscription-admin role providing
this access.
See the failing job:
https://app.travis-ci.com/github/stolostron/canary/builds/247478348
Resolves:
https://github.com/stolostron/backlog/issues/20350
> Grant the subscription-admin user admin access to the test namespace

- Makefile
- build/install-cert-manager.sh
v1.0.1 is too old and it crashes due to using
mutatingwebhookconfiguration v1beta1 api
> Upgrade cert manager

- test/common/gvr.go
The v0.12.0 release of Kind has removed the CRD v1beta1
> Fix Gatekeeper test on kind v0.12.0

- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
Removing enforcementAction does not always work as the policy is set to 
`musthave`. Explicitly set enforcementAction to deny in the policy to 
ensure the gatekeeper constraint is set to deny to avoid test flakiness.
Also patch the enforcementAction before placing the policy.
> Patch enforcementAction to deny

- build/patch-dev-images.sh
- test/e2e/policySet_e2e_test.go
- test/integration/policy_set_test.go
- test/resources/policy_set/statuscheck-1.yaml
- test/resources/policy_set/statuscheck-2.yaml
- test/resources/policy_set/statuscheck-3.yaml
- test/resources/policy_set/undo-patch-policy-set.yaml
makes framework test compatible with changes to simplify the policySet status field
> remove results field from policyset status check

- test/common/user_management.go
- test/policy-collection/policy_generator_acm_hardening.go
- test/resources/policy_generator/acm-hardening_subscription.yaml
The acm hardening policy set has been moved to a stable directory.
This is a test that will help make sure it continues to have some
validation.
Refs:
- https://github.com/stolostron/backlog/issues/20337
> Create a test for the acm hardening policy set

- Makefile
- doc/development.md
- test/common/gvr.go
- test/integration/policy_certificate_test.go
- test/integration/policy_etcdencryption_test.go
- test/integration/policy_iam_test.go
- test/integration/policy_info_metric_test.go
- test/integration/policy_limitmemory_test.go
- test/integration/policy_namespace_test.go
- test/integration/policy_report_metric_test.go
- test/integration/policy_scc_test.go
- test/integration/policy_set_test.go
Notes:
- Reduces package-level variables to prevent collisions and allow for similarly named variables in each test file
- Adds test for `policy-scc.yaml`
- Along with the package-level variable reduction, with this test file I attempted to establish a boilerplate test format where a new test for a new kind could be written with minimal updates (primarily to the variable declarations at the top) and then built upon
Addresses:
- https://github.com/stolostron/backlog/issues/20846
> Add test for `policy-scc.yaml`

- test/integration/policy_imagemanifest_test.go
- test/integration/policy_pod_test.go
- Drop unnecessary `SVT` label for pod test and remove package-level variables
- Add `BVT` label for imagemanifestvuln test
> Update test labels

- test/integration/policy_imagemanifest_test.go
I see things taking a lot longer in the canary for downstream.
```
STEP: Checking if the status of the subscription config policy is Compliant 04/04/22 10:00:33.838
STEP: Checking if the status of the CSV config policy is Compliant 04/04/22 10:00:43.886
STEP: Checking if the status of the IMV config policy is NonCompliant 04/04/22 10:01:01.986
------------------------------
• [FAILED] [88.149 seconds]
GRC: [P1][Sev1][policy-grc] Test the policy-imagemanifestvuln policy [policy-collection, stable, BVT]
/go/src/github.com/stolostron/governance-policy-framework/test/integration/policy_imagemanifest_test.go:20
[It] stable/policy-imagemanifestvuln should detect imageManifestVulns
/go/src/github.com/stolostron/governance-policy-framework/test/integration/policy_imagemanifest_test.go:107
Begin …
```
> Increate timeout for finding the vulnerable images

- test/integration/policy_generator_acm_hardening_test.go
There are some rbac failures in the placementrules controller that
shows placementdecisions verbs get, list, watch are needed for the
user access of placement.  This may be needed in the tests that
use placementrule too.
Refs:
- https://github.com/stolostron/backlog/issues/21455
> PlacementRule is making calls to PlacementDecisions

- test/integration/policy_imagemanifest_test.go
- test/resources/image-vulnerabilities/vulnerable-pod.yaml
Our container security operator test assumes we'll have a vulnerable
image somewhere.  That's not the case for current downstream 2.5
builds.  Adding a vulnerable image as part of the test case.
Refs:
- https://github.com/stolostron/backlog/issues/21459
> Downstream builds are running with no vulnerable images

- test/integration/policy_imagemanifest_test.go
In downstream builds there were few images that the CSO could scan,
so finding the one with the vulnerability shouldn't take too long. In
upstream there are lots of images that don't have vulnerabilities, so
finding the one with vulnerabilities can take much longer.  My local
testing was finding vulnerabilities within about 3 minutes, so it's
certainly possible the canary test is consistently taking longer than
the 2 minutes allotted.  Logs haven't been useful to identify a root
cause because tests clean up.  Theory on failure is from local tests
Refs:
- https://github.com/stolostron/backlog/issues/21734
> Container image scanning can take a lot of time, increase timeout

- test/integration/policy_imagemanifest_test.go
Remove the BVT label. This will no longer be run in BVTs, only in
other test runs.
Refs:
- https://github.com/stolostron/backlog/issues/21758
> Remove BVT label from test that can take a lot of time

- test/common/common.go
- test/common/user_management.go
- test/integration/policy_generator_acm_hardening_test.go
Are we corrupting the hub kubeconfig?  Printing it out to find out.
The one we create is usually less than 900 bytes so I think if we
overwrite the hub kubeconfig with the e2e one it will be obvious from
the trace -- but this won't necessarily help us know why.
Refs:
- https://github.com/stolostron/backlog/issues/22014
> Add some debug info to try to analyze canary issue

- test/common/common.go
- test/integration/policy_generator_acm_hardening_test.go
My kubeconfigs I thought were smaller than 1024, but I guess they only
ran against bigger ones in testing.
Refs:
- see CI failure in grc repo
> Failure when the kubeconfig is smaller than my slice index

- go.mod
- go.sum
Attempts to address this error:
```
ginkgo -v --slowSpecThreshold=10 test/e2e
Failed to compile e2e:
../../../../pkg/mod/github.com/fsnotify/fsnotify@v1.4.9/inotify.go:19:2: missing go.sum entry for module providing package golang.org/x/sys/unix (imported by github.com/onsi/ginkgo/internal/remote); 
to add:
go get github.com/onsi/ginkgo/internal/remote@v1.16.5
FAIL	github.com/stolostron/governance-policy-framework/test/e2e [setup failed]
FAIL
```
> [release-2.3] Fix Ginkgo dependency errors

- Makefile
- go.mod
- go.sum
- test/common/common.go
- test/e2e/cert_policy_test.go
- test/e2e/configuration_policy_test.go
- test/e2e/gatekeeper_test.go
- test/e2e/hub_templates_encryption_test.go
- test/e2e/iam_policy_test.go
- test/e2e/policySet_e2e_test.go
- test/integration/integration_suite_test.go
- test/integration/policy_certificate_test.go
- test/integration/policy_comp_operator_test.go
- test/integration/policy_etcdencryption_test.go
- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/integration/policy_gatekeeper_operator_test.go
- test/integration/policy_hub_templates_21440_test.go
- test/integration/policy_iam_test.go
- test/integration/policy_imagemanifest_test.go
- test/integration/policy_info_metric_test.go
- test/integration/policy_limitmemory_test.go
- test/integration/policy_namespace_test.go
- test/integration/policy_pod_test.go
- test/integration/policy_psp_test.go
- test/integration/policy_report_metric_test.go
- test/integration/policy_role_test.go
- test/integration/policy_rolebinding_test.go
- test/integration/policy_scc_test.go
- test/integration/policy_set_test.go
This also adds in changes from running `make fmt`.
Related:
https://github.com/stolostron/backlog/issues/21790
> Use the new Policy Propagator module name in imports

- test/common/common.go
- test/integration/policy_generator_acm_hardening_test.go
The debug logging has not helped to isolate the placement controller
issue with patching rules.
> Remove debug logging

- test/integration/policy_generator_test.go
This test hasn't been stable in canaries, but works great when run
in local environments.  I think increasing the timeout may help
Refs:
- https://github.com/stolostron/backlog/issues/22546
> Increase the timeout in the generator test for placement propagation

- Makefile
- test/resources/policy_generator/subscription.yaml
The lack of the PolicySet kind in the allow list for the subscription
is now breaking the geneator test.
> The allow list missing policyset is breaking the generator subscription

- Makefile
- build/run-test-kind-prow.sh
We'll need to update the `api` commit hash each time we update packages, but this will at least make it so that we won't have to update the release branch each time.
> Set release branch to a variable

- test/e2e/hub_templates_encryption_test.go
- test/integration/policy_certificate_test.go
- test/integration/policy_comp_operator_test.go
- test/integration/policy_etcdencryption_test.go
- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/integration/policy_gatekeeper_operator_test.go
- test/integration/policy_generator_acm_hardening_test.go
- test/integration/policy_generator_test.go
- test/integration/policy_hub_templates_21440_test.go
- test/integration/policy_iam_test.go
- test/integration/policy_imagemanifest_test.go
- test/integration/policy_info_metric_test.go
- test/integration/policy_limitmemory_test.go
- test/integration/policy_namespace_test.go
- test/integration/policy_pod_test.go
- test/integration/policy_psp_test.go
- test/integration/policy_report_metric_test.go
- test/integration/policy_role_test.go
- test/integration/policy_rolebinding_test.go
- test/integration/policy_scc_test.go
- test/integration/policy_set_test.go
Since fail-fast was turned on for the tests, some of the "clean up" test
nodes are not being run. A better fit for those is "AfterAll" nodes,
which require the Describes to be marked as Ordered.
In addition, some BeforeEach test nodes would fit better as BeforeAll,
since that is now possible.
Note: adding "Ordered" to the Describes largely does not change the
behavior. Unless the `--randomize-all` flag is passed, the It nodes
will be run in the order they are defined anyway.
> Use Ordered Describes and After/BeforeAll nodes

- .travis.yml
- build/set-claim.sh
This implements a hibernation flow that wakes up the `grce2e-policy-grc-cp-prow` ClusterClaim prior to the tests and hibernates it on completion.
Related to:
- https://github.com/stolostron/backlog/issues/14845
> Hibernate E2E cluster when not in use

- Makefile
- build/run-test-kind-prow.sh
- test/resources/policy_generator/subscription.yaml
This fixes a testcase that is failing because the allow list does not
include PolicySets.  The policy set resource is version v1beta1 so
including that version in the allow list.
Refs:
- https://github.com/stolostron/backlog/issues/22546
> Backport the policy generator test fix to release-2.5

- .travis.yml
It didn't occur to me that the labyrinth that is `build-harness-extensions` handled the install. This calls the `oc/install` target directly.
> Install `oc` before `set-claim.sh` script

- .travis.yml
- build/set-claim.sh
It's not working, but I shouldn't have relied on the build-harness when we have a script that installs `oc` already.
> Use script instead of Make target

- build/run-e2e-tests-policy-framework-prow.sh
- build/run-test-kind-prow.sh
This addresses the "cut a new release" script deficiency by allowing us to remove the environment variable from Prow and set it dynamically using a Prow variable, similar to this recently implemented code: https://github.com/stolostron/governance-policy-framework/blob/8006a5e88d3649647f3202caf6c1a739c2786d52/build/run-test-kind-prow.sh#L36-L39
> Use Prow variable for dynamic image tag

- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/integration/policy_gatekeeper_operator_test.go
The audit pod was previously failing with OOMKilled. A setting was added
to avoid that, but it may slow down the audit process, so this timeout
needs to be lengthened.
Refs:
- https://github.com/stolostron/backlog/issues/23005
> Increase timeout for gatekeeper sample compliance

- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/integration/policy_gatekeeper_operator_test.go
- test/integration/policy_kyverno_generators_test.go
- test/resources/gatekeeper/policy-gatekeeper-operator.yaml
Kyverno policies are also just called "policy", so the tests need to be
a little more specific when dealing with open-cluster-management.io
policies through kubectl commands.
In addition, the gatekeeper operator `latest` image was recently updated, and we need to pin to a specific version in order to keep it working.
> Add qualified policy type name and pin gatekeeper operator version

- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/integration/policy_gatekeeper_operator_test.go
- test/integration/policy_kyverno_generators_test.go
- test/integration/policy_report_metric_test.go
The audit pod is taking a long time to complete and populate a field that the sample gatekeeper policy is checking for. This increases the timeout on that test, and should gather some information we can use to track how long the process is taking as the cluster ages.
> Gk audit timing

- build/periodic.sh
There was a minor update to `grc-ui` that failed in CI but got missed since it was removed from the repo list. This manually adds deprecated repos to our script.
> Manually add deprecated UI repos to CI check

- test/integration/policy_kyverno_generators_test.go
Cleanup can be a concern when the tests are run on a long running
cluster.  This change makes sure cleanup is called.
Refs:
- https://github.com/stolostron/backlog/issues/22938
> Address cleanup concern when kyverno tests fail

- test/integration/policy_kyverno_generators_test.go
This impacts our e2e tests which have problems installing kyverno, but
this is really just a cleanup fix.  I don't think it solves the problem
with e2e failures, but it may help.
> Kyverno cleanup is not properly removing the policy

- test/integration/policy_info_metric_test.go
- test/integration/policy_report_metric_test.go
- test/resources/policy_info_metric/metrics_role.yaml
- test/resources/policy_info_metric/metrics_token.yaml
- test/resources/policy_info_metric/nometrics_token.yaml
- test/resources/policy_report_metric/metrics_token.yaml
In newer versions of Kubernetes, tokens are not automatically created
for all service accounts. Therefore, the tests might need to manually
create the tokens for the service accounts it uses.
There is also a new test for users that should not have access to the
endpoint, whereas previously we only tested unauthenticated access.
Refs:
- https://github.com/stolostron/backlog/issues/24075
> Improve policy_governance_info metric RBAC tests

- test/integration/policy_kyverno_generators_test.go
Since this CRD is installed by ACM, but also Kyverno as part of its Helm
chart, when the subscription is removed, the CRD is also removed. But
some ACM components still need it.
This just reapplies the CRD after the Helm Release is cleaned up.
> Reapply PolicyReport CRD after kyverno test

- test/integration/policy_imagemanifest_test.go
This test is flaky and the errors are almost never indicative of an
actual issue with the GRC code. This should be an SVT test instead for
those reasons.
> Move the policy-imagemanifestvuln test to SVT

- test/integration/policy_kyverno_generators_test.go
Failure in SVT test due to the kubeconfig being used was managed cluster
kubeconfig instead of hub.
Refs:
- https://github.com/stolostron/backlog/issues/24410
> Use the hub kubeconfig to patch the placement

- test/common/gvr.go
- test/configuration_policy_prune.go
- test/e2e/e2e_suite_test.go
- test/resources/configuration_policy_prune/cm-policy-prune-all.yaml
- test/resources/configuration_policy_prune/cm-policy-prune-default.yaml
- test/resources/configuration_policy_prune/cm-policy-prune-if-created.yaml
- test/resources/configuration_policy_prune/cm-policy-prune-none.yaml
- test/resources/configuration_policy_prune/configmap-only.yaml
Tests the general functionality of this new feature.
These tests are in a new (experimental) format that allow them to
be run in our usual KinD tests (under e2e) as well as in our larger set
of tests that run against real clusters (under integration). This
format would also potentially allow us to turn tests on and off
separately from the ginkgo filters, which could be helpful because the
filters cause tests to be *skipped*, which impacts test execution stats.
Refs:
- https://github.com/stolostron/backlog/issues/24440
> Add tests for pruneObjectBehavior feature

- test/e2e/hub_templates_encryption_test.go
- test/integration/policy_certificate_test.go
- test/integration/policy_comp_operator_test.go
- test/integration/policy_etcdencryption_test.go
- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/integration/policy_gatekeeper_operator_test.go
- test/integration/policy_generator_acm_hardening_test.go
- test/integration/policy_generator_test.go
- test/integration/policy_hub_templates_21440_test.go
- test/integration/policy_iam_test.go
- test/integration/policy_imagemanifest_test.go
- test/integration/policy_info_metric_test.go
- test/integration/policy_limitmemory_test.go
- test/integration/policy_namespace_test.go
- test/integration/policy_pod_test.go
- test/integration/policy_psp_test.go
- test/integration/policy_report_metric_test.go
- test/integration/policy_role_test.go
- test/integration/policy_rolebinding_test.go
- test/integration/policy_scc_test.go
- test/integration/policy_set_test.go
Backport of PR https://github.com/stolostron/governance-policy-framework/pull/331 to release-2.5 for issue:
- https://github.com/stolostron/backlog/issues/23871
Since fail-fast was turned on for the tests, some of the "clean up" test
nodes are not being run. A better fit for those is "AfterAll" nodes,
which require the Describes to be marked as Ordered.
In addition, some BeforeEach test nodes would fit better as BeforeAll,
since that is now possible.
Note: adding "Ordered" to the Describes largely does not change the
behavior. Unless the `--randomize-all` flag is passed, the It nodes
will be run in the order they are defined anyway.
> Use Ordered Describes and After/BeforeAll nodes (#331)

- build/download-clis.sh
- build/run-e2e-tests.sh
Some recent failures have been caused by the openshift client version;
when a test exposes a service as a route, it provides an `--overrides`
paramter that was being ignored in newer client versions.
> Pin the oc client version to 4.10.21

- test/e2e/gatekeeper_test.go
- test/integration/policy_comp_operator_test.go
- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/integration/policy_gatekeeper_operator_test.go
- test/integration/policy_set_test.go
When an assertion is made in an `Eventually`, it must use the input
`Gomega` argument to avoid a failed assertion from failing the
`Eventually` before it times out.
One example is a flaky network connection failure an SVT test:
https://github.com/stolostron/backlog/issues/24895
> Fix assertions wrapped in Eventuallys

- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/integration/policy_gatekeeper_operator_test.go
If the operator doesn't install, this should log why.  Typical failures
have been image pull issues from OLM, but resource issues could be
detected too.
Refs:
- https://github.com/stolostron/backlog/issues/23871
> Minor update to log gatekeeper operator install problem

- test/e2e/configuration_policy_test.go
- test/e2e/gatekeeper_test.go
- test/integration/policy_comp_operator_test.go
- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/integration/policy_gatekeeper_operator_test.go
- test/integration/policy_set_test.go
A cherry-pick from #425.
When an assertion is made in an `Eventually`, it must use the input
`Gomega` argument to avoid a failed assertion from failing the
`Eventually` before it times out.
One example is a flaky network connection failure an SVT test:
https://github.com/stolostron/backlog/issues/24895
(cherry picked from commit 2bb05ee26dc322044b7703426545bc97b994967c)
> [release-2.5] Fix assertions wrapped in Eventuallys

- build/run-e2e-tests.sh
This prevents GitHub rate limiting causing failures in the tests. It
additionally provides a consistent version on each test run to improve the
stability of the tests.
This also makes the run-e2e-tests.sh script fail on HTTP errors.
> Pin the kind CLI version

- Makefile
Recently, OLM 0.22.0 was released which didn't contain the install.sh
script in the GitHub release assets and caused the policy framework
tests to fail. This pins the version to prevent that.
> Pin the OLM version

- test/e2e/configuration_policy_test.go
- test/e2e/gatekeeper_test.go
- test/policy-collection/policy_comp_operator_test.go
- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
This is cherry-picked from #431 and #425.
When an assertion is made in an `Eventually`, it must use the input
`Gomega` argument to avoid a failed assertion from failing the
`Eventually` before it times out.
One example is a flaky network connection failure an SVT test:
https://github.com/stolostron/backlog/issues/24895
(cherry picked from commit 2bb05ee26dc322044b7703426545bc97b994967c)
(cherry picked from commit 3851dd635f77a2b5435db2210e12e40572dab477)
> [release-2.4] Fix assertions wrapped in Eventuallys

- .github/workflows/e2e.yml
- .github/workflows/kind.yml
Previously, we added actions to many component repositories to run these
tests on their own PRs, helping to ensure things continued to work well
together. This brings that work into this repository, so that those
repositories do not need to maintain the workflow individually.
It also includes new enhancements to improve the experience on GitHub,
for example saving debug information for download during a failure, and
saving test reports for possible future use. These are accessible from
the summary page of the action run.
Finally, it adds a local call of the workflow on pushes and PRs, which
could replace some other tool's invocation of the tests.
Refs:
- https://github.com/stolostron/backlog/issues/22914
> Add reusable workflow for running KinD tests

- test/common/common.go
- test/common/user_management.go
- test/integration/integration_suite_test.go
- test/integration/policy_comp_operator_test.go
- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/integration/policy_gatekeeper_operator_test.go
- test/integration/policy_generator_test.go
- test/integration/policy_iam_test.go
- test/integration/policy_imagemanifest_test.go
This matches the interval in `policy_generator_acm_hardening.go`. It also updates a deprecated `ioutils` function.
> Extend login retry interval

- test/integration/policy_comp_operator_test.go
https://github.com/stolostron/backlog/issues/25465
The failure in the issue was difficult to reproduce, which means it probably only happens occasionally, and we expect these pods to get cleaned up eventually on their own. After talking with @dhaiducek the best course of action seems to be to just remove the cleanup check, and we can address it in the future in the event the pods aren't being cleaned up properly.
> remove compliance operator pod cleanup check

- Makefile
- test/integration/policy_gatekeeper_operator_test.go
There's a newline or some whitespace in there that the equality wasn't catching
Followup to:
- https://github.com/stolostron/governance-policy-framework/pull/445
> Fix Gatekeeper namespace creation detection

- test/integration/policy_gatekeeper_operator_downstream_test.go
I am slightly horrified I missed the second update in the downstream gatekeeper test. I've updated the cherry-picks to include both. This is a followup to:
- #463
> Use substring for creation detection (downstream)

- Makefile
- test/e2e/gatekeeper_test.go
This also pins the Kubernetes version to v1.24 for the latest to workaround:
https://github.com/stolostron/backlog/issues/25698
> Output the Gatekeeper pods when the deployment fails

- test/integration/policy_kyverno_generators_test.go
The canary test failed because it's looking for a non-compliant policy on the managed cluster but the kyverno install policy only deploys itself to the hub.  It has an embedded helm chart which goes to the managed cluster.  Changed the namespace check.
Refs:
- https://github.com/stolostron/backlog/issues/25798
> Kyverno test case failure in canary check wrong cluster

- test/policy-collection/policy_gatekeeper_operator_downstream_test.go
- test/policy-collection/policy_gatekeeper_operator_test.go
A canary test failure that I think may be due to a missing change in the 2.4 release.  Linking the canary issue and the related PR below.
Refs:
- https://github.com/stolostron/backlog/issues/25851
- https://github.com/stolostron/governance-policy-framework/pull/286
> Address possible problem with gatekeeper changing dryrun to deny

- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/integration/policy_gatekeeper_operator_test.go
Without finding a real root cause for a gatekeeper canary failure I'm hoping adding some debugging logs may help get us closer to figuring out what may have broken. I think for now we will focus on the hub side policies to make sure patches applied at runtime are working.
Refs:
- https://github.com/stolostron/backlog/issues/25903
> Add some gatekeeper debugging that may help figure out canary failure

- .github/workflows/sonarcloud.yml
This reusable workflow allows securely calling SonarCloud on PRs from forks and pushes to branches.
Relates:
https://github.com/stolostron/backlog/issues/25949
> Add a reusable GitHub workflow for running SonarCloud

- .github/workflows/sonarcloud.yml
Relates:
https://github.com/stolostron/backlog/issues/25949
> Require the SONAR_TOKEN secret in the sonarcloud reusable workflow

- Makefile
This way we don't need to keep track of whether the commit hash needs to be updated.
> Use `api` tag from `go.mod`

- test/integration/policy_kyverno_generators_test.go
Backport https://github.com/stolostron/governance-policy-framework/pull/475 to release-2.6
We have decided to backport the entire 2.7 release framework test to 2.6, this is a quick fix before that task is done.
Refs:
- https://github.com/stolostron/backlog/issues/26036
> [release-2.6]  Kyverno test case failure in canary check wrong cluster

- .github/workflows/sonarcloud.yml
Without it, SonarCloud seems to assume things are happening on `main`.
> Set the branch name on pushes for SonarCloud

- .travis.yml
It seems there's something happening to cause the E2E user to be logged out mid-test. Until that can be resolved, we should probably keep the cluster running.
> Revert Hibernation

- Makefile
`make` will run the first target it encounters as a default. Since our linting was included first, the first target there was `yaml-lint`, which was failing.
Alternatively, we could remove the argument-less `make` command, but I wasn't sure of the effect of that.
> Make `default` the default

- test/integration/policy_report_metric_test.go
This commit was erroneously cherry-picked to 2.5, but the Insights client only changed in newer versions.
> Revert "Update insights client and metrics selector" for 2.5

- test/common/gitops_utils.go
- test/common/user_management.go
- test/integration/policy_generator_acm_hardening_test.go
- test/integration/policy_generator_remote_test.go
- test/integration/policy_generator_test.go
This tests the functionality to provide a remote Kustomize directory to `manifests[].path`
Depends on:
- PolicyGenerator Kustomization (pointing to the `grc-e2e-policy-generator-test` repo): 
- #496 
- Remote Kustomization: 
- https://github.com/stolostron/grc-e2e-policy-generator-test/pull/3
ref: 
- https://github.com/stolostron/backlog/issues/25928
> Add remote Kustomize generator E2E tests

- build/run-e2e-tests.sh
- test/common/common.go
- test/integration/policy_comp_operator_test.go
- test/integration/policy_imagemanifest_test.go
- test/integration/policy_kyverno_generators_test.go
Previously, we were somewhat limited because the tests run in Travis, whichmight assume things are broken and abort the tests if nothing is written to stdout in a while. Now, a one-liner will prevent that, so we can increase the maximum timeout.
Refs:
- https://github.com/stolostron/backlog/issues/26165
> Increase maximum test time

- test/common/gitops_utils.go
- test/common/user_management.go
A `-user` suffix that was removed in the refactor had inadvertently been left behind when deleting the Identity objects.
This PR also shuffles commands to delete user-specific objects first and adds additional headings to make cleanup steps more visible.
I'm not 100% sure it'll help, but hopefully it will. I've cleaned up leftover Identities, so if the next run passes it's probable that this PR will address the failures:
```
$ oc delete identity --all
identity.user.openshift.io "grc-e2e-hardening-sub-admin-user:grc-e2e-subscription-admin" deleted
identity.user.openshift.io "grc-e2e-subadmin-user-hardening:grc-e2e-subadmin-user-hardening" deleted
identity.user.openshift.io "grc-e2e-subadmin-user-hardening:grc-e2e-subadmin-user-polgen" deleted
identity.user.openshift.io …
```
> Remove `-user` suffix from IDP name in cleanup

- build/periodic.sh
We have CRDs synced to `multiclusterhub-operator` and an action running already that checks the `governance-policy-addon-controller`. This adds a check to make sure both of those are up-to-date/passing.
Note that this check will currently be failing until this PR is merged:
- https://github.com/stolostron/multiclusterhub-operator/pull/885
> Add CRD sync checking to the periodic CI script

- test/integration/policy_kyverno_generators_test.go
This avoids a race condition where the webhooks are still present but Kyverno is down and blocks API actions. This also fixes a typo in one of the Kyverno webhook deletion commands.
> Delete the Kyverno webhooks before the deployment 

- test/common/policy_utils.go
- test/configuration_policy_prune.go
- test/integration/policy_kyverno_generators_test.go
- test/integration/policy_set_test.go
Gomega seems to ignore the Eventually calls if there is no assertion on them.
> Add missing assertions on Eventually calls

- test/integration/policy_kyverno_generators_test.go
This shifts deleting the webhooks up in the Eventually so it is deleted again in the event of a race condition.
> Set timeouts when deleting the Kyverno namespaces

- build/periodic.sh
We added an OWNERS file to the `multiclusterhub-operator` repo that needs to be ignored.
> Skip OWNERS file in CRD check

- test/common/gitops_utils.go
I've seen this happen a few times and figure it can't hurt to increase the timeout.
> Increase the timeout when deleting the GitOps test namespace

- test/common/gvr.go
- test/integration/policy_generator_acm_hardening_test.go
- test/integration/policy_kyverno_generators_test.go
This is also adds back deleting the mutation webhooks which was removed by accident in a previous commit.
Relates:
https://github.com/stolostron/backlog/issues/26834
> Delete the Kyverno subscription on the Hub

- build/patch-dev-images.sh
- test/common/gitops_utils.go
- test/common/user_management.go
- test/integration/policy_generator_acm_hardening_test.go
- test/integration/policy_generator_remote_test.go
- test/integration/policy_generator_test.go
The expectation is that identities would have the pattern `<username>:<username>` because we expect the username to match the IDP. But in case there was a stale IDP, and it's somehow used we want to make sure to clean it up also.
> Clean up any stale identities

- build/periodic.sh
The CICD GitHub token was invalid, so our periodic job couldn't clone the repos. I thought about handling the single false positive to let it all pass, but I think it'd be better that we knew about when the clone doesn't succeed and short circuit the checks.
> Handle when repos can't be cloned

- test/integration/verify_metrics_test.go
- test/resources/verify_metrics/metrics_token.yaml
- test/resources/verify_metrics/noncompliant.yaml
Note that the spec-sync metrics are skipped due to it not being available on a self-managed Hub. The presence of the other sync metrics indicate that the metrics are exported from governance-policy-framework addon properly. Other metrics that require error conditions to show up are also skipped.
Relates:
https://issues.redhat.com/browse/ACM-2452
> Test that the required default metrics are present

- Makefile
- test/configuration_policy_prune.go
Tests that the ConfigurationPolicy CRD does not become stuck due to pruneObjectBehavior finalizers when the controller is uninstalled.
Refs:
- https://issues.redhat.com/browse/ACM-2923
> Add test for configpolicy cleanup during uninstall

- .travis.yml
This was overlooked when the build harness was removed.
> Install the oc client in the TravisCI job

- test/configuration_policy_prune.go
The Deployment finalizer was removed so this test can also be removed.
Relates:
https://issues.redhat.com/browse/ACM-3233
https://issues.redhat.com/browse/ACM-2923
> Remove the config-policy-controller Deployment finalizer test

- build/periodic.sh
- test/common/policy_utils.go
- test/e2e/cert_policy_test.go
- test/e2e/configuration_policy_test.go
- test/e2e/iam_policy_test.go
Signed-off-by: Yi Rae Kim <yikim@redhat.com>
from ACM-3075
GRC Policies have tests that check for a compliance or noncompliance and then some action is taken so that the compliance state changes.  It would be useful after one of these tests, to take a look at the compliance history and see if it was updated as expected. 
This has been proposed as the result of sprint retrospective discussion.
> add lastest msg check

- .github/workflows/kind.yml
- Makefile
In favor of setting the tag directly, this reverts:
- #558 
https://issues.redhat.com/browse/ACM-3490
> Update VERSION_TAG to latest-2.8

- test/integration/policy_iam_test.go
In one test run, the group was left behind, which made future test runs fail earlier, and it would never recover automatically.
> Ensure the iam group is cleaned up

- test/common/common.go
- test/common/gitops_utils.go
- test/integration/integration_suite_test.go
- test/integration/policy_generator_acm_hardening_test.go
- test/integration/policy_generator_remote_test.go
- test/integration/policy_generator_test.go
This should reduce flakiness caused by the auth pods restarting each time we create a new gitops user.
Refs:
- https://issues.redhat.com/browse/ACM-2423
> Use a common GitOps user for generator tests

- go.mod
- go.sum
- test/integration/policy_kyverno_generators_test.go
Even after the permissions bug fix, the Kyverno test failure has been lingering in our E2E tests.
> Bump Kyverno test timeouts

- Makefile
Gatekeeper is able to run on v1.25 now.
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
> Remove Gatekeeper workaround

- test/common/gitops_utils.go
- test/integration/integration_suite_test.go
If subscription admin setup (specifically, logging in) fails, cleanup doesn't have the populated OCPUser to work with. Using a pointer populates the values so that cleanup can succeed in that case.
> Pass a pointer for OCPUser

- build/run-e2e-tests-policy-framework-prow.sh
Not sure how this got missed previously, but the script somehow wasn't actually using the `VERSION_TAG`.
> Use `VERSION_TAG` in patch

- test/common/policy_utils.go
- test/e2e/configuration_policy_test.go
Prior to this, the test would check the compliance messages at the end of the test, however, this could run into race conditions. For example, if a policy becomes compliant due to updating an object, an additional status message can be added if the Config Policy controller manages to perform another evaluation before the test moves on.
This check adds the status message checks at each step so that the test waits for all expected status messages to appear before moving on.
This should unblock the CI failure here:
https://github.com/stolostron/governance-policy-framework-addon/pull/53
There seemed to be race conditions encountered where consecutive tests
that used the same policy, would sometimes have status events from the
previous test get added even if the events were deleted. This is …
> Wait for the compliance messages in the configuration policy tests

- test/integration/hubtemplates_managedclusterlabels_test.go
- test/resources/hub_templates_managedclusterlabels/hub-configmap.yaml
- test/resources/hub_templates_managedclusterlabels/mclabels-fromcm-pol.yaml
- test/resources/hub_templates_managedclusterlabels/mclabels-range-pol.yaml
One test is added to the BVT, one is SVT-only. I was planning on having an additional test to check that if a label is queried that doesn't exist, then the policy would be non-compliant (I thought that such an error would appear as a template-error), but the Go stdlib `template` inserts `<no value>` in that situation. That might not be ideal, but it's not something to fix at this moment.
Refs:
- https://issues.redhat.com/browse/ACM-4177
> Test ManagedClusterLabels in hub templates

- build/run-e2e-tests.sh
The label was changed in a recent commit to the framework-addon.
Refs:
- https://github.com/stolostron/governance-policy-framework-addon/commit/2c5eacdea6ed5f1e6188ce8974519ea20af3657f#diff-bd3800bb3752e57b831a39f0fbe95304375cccdda87daf525fe9a4a841c66bef
> Use app instead of name for the fw-addon selector

- .github/workflows/repo-config.yml
Threading on the Slack message would require increased OAuth in the Slack app, so this leverages the GitHub summary to view the results instead: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
If we want to increase the content of the Slack message in the future, that is also a possibility. (We could even post the log files as attachments, but that's a legacy, though not deprecated, functionality: https://api.slack.com/messaging/composing/layouts#attachments)
> Add results to CI workflow summary

- build/common.sh
We are seeing an issue in our prow: 
```
fatal: destination path 'stolostron/policy-generator-plugin' already exists and is not an empty directory.
[64](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-stolostron-governance-policy-framework-main-periodic-build/1649292036634841088#1:build-log.txt%3A64)
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"[k8s.io/test-infra/prow/entrypoint/run.go:79](http://k8s.io/test-infra/prow/entrypoint/run.go:79)","func":"[k8s.io/test-infra/prow/entrypoint.Options.Run](http://k8s.io/test-infra/prow/entrypoint.Options.Run)","level":"error","msg":"Error executing test process","severity":"error","time":"2023-04-21T06:07:12Z"}
[65](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-stolos …
```
> Remove policy generator

- .github/workflows/repo-config.yml
- `ACTION_RESULT` had not been stored in the `GITHUB_ENV` file, so it couldn't be retrieved
- Also cleans up the Slack and summary posts
Followup to this steadily growing list 😂 :
- #606 
- #604 
- #603
> Store `ACTION_RESULT` properly

- .github/workflows/e2e.yml
- .github/workflows/kind_host.yml
- .gitignore
- Makefile
- test/common/common.go
- test/common/policy_utils.go
- test/configuration_policy_prune.go
- test/e2e/cert_policy_test.go
- test/e2e/configuration_policy_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/hub_templates_encryption_test.go
- test/e2e/iam_policy_test.go
- test/e2e/policySet_e2e_test.go
- test/integration/integration_suite_test.go
- test/policy_ordering.go
- test/resources/hosted_mode/managed-cluster-addon.yaml
Add basic tests for ACM Policies in hosted mode in the policy framework E2E tests
We currently test that hosted mode deployments of the policy controllers work as expected on PRs to the Policy Addon controller. This is good for testing changes in how the controllers are deployed but it doesn't test their functionality in hosted mode and it also doesn't gate code changes the policy controllers.
GRC currently has E2E and other integration tests in the stolostron/governance-policy-framework repo that gate code changes from being fast-forwarded to a release branch and thus getting into a release build. A new E2E test should be added that tests the policy controllers in hosted mode.
Since these E2E tests are already executed on PR CI in the Stolostron repos before an upstream PR is synced, …
> Add basic tests for ACM Policies in hosted mode in the policy framework E2E tests

- build/run-test-image.sh
- test/common/common.go
- test/integration/integration_suite_test.go
- test/integration/policy_info_metric_test.go
- test/integration/policy_report_metric_test.go
The namespace where some of the open-cluster-management resources live is not *always* just "open-cluster-management". It is configurable.
Refs:
- https://issues.redhat.com/browse/ACM-4970
> Add flag for ocm namespace configuration

- build/clean-up-cluster.sh
Newer versions of kubernetes do not have a PodSecurityPolicy type, so this cleanup script was failing. Now cleaning up that object works like other objects that might not have their types defined on the cluster.
> Allow cleaning psp to fail if not installed

- build/main-branch-sync/README.md
- build/main-branch-sync/fetch-repo-list.sh
- build/main-branch-sync/upstream-release.sh
Adds an `upstream-release.sh` script to push a new tag to upstream controllers. (The GitHub Action in the repo will create the draft release to be published.)
> Add script for upstream releases

- build/codebase-check.sh
- build/main-branch-sync/README.md
- build/main-branch-sync/rotate-secrets.sh
`codebase-check.sh`
- `rc` exit code was mistakenly being overwritten
`rotate-secrets.sh`
- Add `oc` version check
- Add absolute path for `repo*.txt`
- Add token rotation for framework Actions
> Script fixes

- build/run-test-image.sh
- test/common/common.go
- test/integration/integration_suite_test.go
- test/integration/policy_gatekeeper_operator_downstream_test.go
This is to disable the Gatekeeper status controller. This would happen automatically, but it can take a while since it relies on the health endpoint.
Relates:
https://issues.redhat.com/browse/ACM-5965
> Restart the governance-policy-framework addon after Gatekeeper is uninstalled

- Makefile
- test/common/gitops_utils.go
Attempts to fix the flaky GitOps user login by monitoring the oauth deployment for readiness
Also uses the `.go/` directory for the addon-controller so that it's hidden and not at the root of the repo when it exists.
ref: https://github.com/stolostron/backlog/issues/27338
> Add oauth deployment checks

- .github/workflows/e2e.yml
- .github/workflows/kind.yml
- Makefile
- Shorten debug log output (The dump, now that it is fixed, was causing Travis to run out of logging space)
- Remove `--fail-fast` as a default Ginkgo argument 
- Adjust E2E regex to include all releases - (It used to be that we didn't want it to run on 2.6, but now we do want it to run on 2.9+)
- Make `TEST_FILE` usage cleaner
> Adjust E2E default configurations

- test/common/common.go
- test/common/gitops_utils.go
Bumping timeouts isn't ideal, but in this case (namespace deletion and OAuth configuration), we're waiting on other processes to complete, so we can give this a shot for now. (Though it does make me wonder if I should remove the deployment check instead and just bump the login timeout for simplicity...)
> Bump GitOps timeouts

- Makefile
- test/resources/cert_policy/certificate.yaml
- test/resources/cert_policy/certificate_allow-noncompliant.yaml
- test/resources/cert_policy/certificate_compliant.yaml
- test/resources/cert_policy/certificate_disallow-noncompliant.yaml
- test/resources/cert_policy/certificate_expired-ca.yaml
- test/resources/cert_policy/certificate_long-ca.yaml
- test/resources/cert_policy/certificate_long.yaml
- test/resources/cert_policy/issuer.yaml
https://github.com/stolostron/governance-policy-propagator/pull/419 The framework test has an issue because of the miss-matching cert-manger version.  Therefore, this PR will upgrade cert-manager to the latest version. 
Ref: https://cert-manager.io/docs/installation/api-compatibility/#alpha--beta-api-versions 
https://issues.redhat.com/browse/ACM-3558
> Cert-manager version upgrade

- build/README.md
- build/detect-modules.sh
Sample output:
```
$ ./detect-packages.sh goproxy
Go module query: goproxy
* Checking stolostron/cert-policy-controller
CGO_ENABLED=1 go build -o ./build/_output/bin/cert-policy-controller ./main.go
=== stolostron/cert-policy-controller 2.6: goproxy not found
CGO_ENABLED=1 go build -o ./build/_output/bin/cert-policy-controller ./main.go
=== stolostron/cert-policy-controller 2.7: goproxy not found
CGO_ENABLED=1 go build -o ./build/_output/bin/cert-policy-controller ./main.go
=== stolostron/cert-policy-controller 2.8: goproxy not found
CGO_ENABLED=1 go build -o ./build/_output/bin/cert-policy-controller ./main.go
=== stolostron/cert-policy-controller 2.9: goproxy not found
. . .
```
~It lacks a summary currently, but~ it definitely speeds up searching for modules in our binaries. 🙂
> Add script to detect Go modules

- build/run-test-image.sh
When the placement-rule controller is running (like it is in *VT or our integration tests), the placement rule does not need to be "manually" patched with placement decisions. Trying to patch the placement rule can lead to conflicts which fail the test.
Refs:
- https://github.com/stolostron/backlog/issues/27366
> Stop patching placement decisions in integration

- build/main-branch-sync/refresh.sh
When run outside of the script directory, the path to the `README.md` was incorrect.
> Set an absolute path for the refresh script

- test/integration/policy_comp_operator_test.go
The compliance operator test sometimes fails because the scan doesn't complete within the timeout. The check for DONE should be removed to speed up the test and reduce flakiness.
Ref: https://issues.redhat.com/browse/ACM-8238
> Fix flaky complicance operator test

- .github/workflows/repo-config.yml
- build/codebase-check.sh
- build/periodic.sh
- Uses `awk` to replace newlines with literal `\n` for the JSON string
- Doesn't create the summary file on success so that nothing extra is posted to Slack in that case
> Fix JSON for Slack message

- build/clean-up-cluster.sh
- test/resources/policy_generator/acm-hardening_subscription.yaml
- test/resources/policy_generator/remote-kustomization/policyGenerator.yaml
- test/resources/policy_generator/subscription-remote.yaml
- test/resources/policy_generator/subscription.yaml
Uses `Placement` and also instantiates the `ManagedClusterSetBinding` for the policy generator tests.
This PR will need to be followed up by changes to the `grc-e2e-policy-generator-test` repo:
- https://github.com/stolostron/grc-e2e-policy-generator-test/blob/89156af7fa9e24bfc88f7025425457ad0d82d75a/kustomize/policyGenerator.yaml#L13-L14
- https://github.com/stolostron/grc-e2e-policy-generator-test/blob/89156af7fa9e24bfc88f7025425457ad0d82d75a/kustomize/policyGenerator.yaml#L41-L42
ref: https://issues.redhat.com/browse/ACM-9052
> Remove deprecated `PlacementRule` for generator tests

- test/resources/policy_generator/subscription.yaml
It's unnecessary and was blocking Placement from being deployed.
> Remove subscription allow list

- .github/workflows/integration.yml
It appears the workflow is comparing a string with a boolean rather than a string with a string
> Fix fast-forward comparison

- .github/workflows/integration.yml
- Makefile
Commit 1: Based on the example at https://docs.github.com/en/actions/learn-github-actions/variables#using-the-vars-context-to-access-configuration-variable-values. I don't know why double quotes doesn't work, but it's worth a try.
Commit 2: Apply the ClusterManagementAddOn resources required for the addon-controller, see https://github.com/open-cluster-management-io/governance-policy-addon-controller/commit/b3d6cf14aa0b620bf47af4f0cef0f97c0e4b6f62
> Fix hosted test workflow

- build/branch-create/create.sh
- build/branch-create/update-release.sh
The trailing zero in 2.10 was getting stripped since it was getting parsed as a float rather than a string.
> Fix Prow update script

- .github/workflows/integration.yml
- build/main-branch-sync/sync.sh
The integration tests take a while to run, so there's a small chance untested changes could make it through when fast-forwarding. This update sets the commit to the start time of the tests, only fast-forwarding to that commit.
ref: https://issues.redhat.com/browse/ACM-9154
> Set commit time for fast-forwarding

- Makefile
- test/common/gitops_utils.go
- test/integration/policy_info_metric_test.go
- test/integration/policy_report_metric_test.go
- test/resources/policy_generator/subscription-remote.yaml
- test/resources/policy_generator/subscription.yaml
Fixes hosted mode tests resulting from governance-policy-addon-controller cherry-picks.
This PR contains cherry-picks (in full or part) of:
- #670 
- #681
- #682
- #683
- #687 
- #699
Specifically, this PR:
- Removes allowList from appsub
- Adds ManagedClusterSetBindings to generator appsub
ref:
- https://github.com/stolostron/backlog/issues/27443
- https://github.com/stolostron/backlog/issues/27444
> [release-2.8] Update integration tests for Placement

- test/common/gitops_utils.go
- test/integration/policy_info_metric_test.go
- test/integration/policy_report_metric_test.go
- test/resources/policy_generator/subscription-remote.yaml
- test/resources/policy_generator/subscription.yaml
This PR contains cherry-picks (in full or part) of:
- #681
- #682
- #683
- #699
Specifically:
- Remove allowList from appsub
- Add ManagedClusterSetBindings to generator appsub
ref:
- https://github.com/stolostron/backlog/issues/27443
- https://github.com/stolostron/backlog/issues/27444
> [release-2.7] Update integration tests for Placement

- test/common/gitops_utils.go
I'm not sure why, but our ManagedClusterSetBindings are for `global`. For some reason, the webhook is blocking it in 2.7/2.8 but not for the more recent versions. Either way, it's probably needed for all versions.
> Add `global` clusterset binding permission

- .github/workflows/kind.yml
The framework needs it to determine whether to install Gatekeeper.
(This is also a test since I'm not 100% sure whether the `matrix` context is available at this scope, but the docs seem to indicate it is: https://docs.github.com/en/actions/learn-github-actions/contexts#matrix-context)
ref:
- https://github.com/stolostron/governance-policy-framework-addon/pull/238
> Set `KIND_VERSION` at the job scope

- Makefile
Available deployments should be more reliable than Ready pods since it relies on MinReadySeconds
rather than just a Ready status.
Workflow failure ref:
```
wait until cert-manager pods are up
kubectl wait deployment -n cert-manager cert-manager --for condition=Available=True --timeout=180s --kubeconfig=/home/runner/work/governance-policy-framework/governance-policy-framework/framework/kubeconfig_hub
deployment.apps/cert-manager condition met
kubectl wait --for=condition=Ready pod -l app.kubernetes.io/instance=cert-manager -n cert-manager --timeout=180s  --kubeconfig=/home/runner/work/governance-policy-framework/governance-policy-framework/framework/kubeconfig_hub
pod/cert-manager-67459fb8df-phcg2 condition met
pod/cert-manager-cainjector-75b8b97c87-rj87r condition met …
```
> Wait for cert-manager deployments to be Available

- test/common/policy_utils.go
- test/e2e/cert_policy_test.go
- test/e2e/configuration_policy_test.go
Under normal operations of the policy controllers, the policy history details should not repeat.  This can happen though if there is a problem where status updates continually trigger new events even if no status is changing.
Refs:
- https://issues.redhat.com/browse/ACM-9360
> Add a test to detect policy history repeating itself

- build/common/Makefile.common.mk
- test/performance/performance.go
- Version bumps were forthcoming due to https://github.com/open-cluster-management-io/governance-policy-propagator/pull/167
- Add links to make finding updated versions easier (feels like this could be done in a script in the future...or maybe even install things from a `go.mod` so we can use `go get -u` to get new versions...)
> Move versions to top of common Makefile

- .github/dependabot.yml
- build/common/Makefile.common.mk
- Make a single Dependabot group (I'm not sure it's necessary to separate these initially)
- Add `go mod tidy` to `fmt` in the common Makefile
> CI Updates (Dependabot; Common Makefile)

- build/common/Makefile.common.mk
See:
https://access.redhat.com/articles/7027073
https://docs.openshift.com/container-platform/4.12/release_notes/ocp-4-12-release-notes.html
> Update the Kind minimum version to match OCP 4.12

- test/integration/policy_generator_acm_hardening_test.go
- test/integration/policy_generator_remote_test.go
- test/integration/policy_generator_test.go
- test/integration/policy_limitmemory_test.go
- test/integration/policy_namespace_test.go
- test/integration/policy_pod_test.go
- test/integration/policy_psp_test.go
- test/integration/policy_role_test.go
- test/integration/policy_rolebinding_test.go
- test/integration/policy_scc_test.go
- test/integration/policy_set_test.go
- Use `HaveOccurred()` consistently
- Ignore unused return values
> Fix error assertions

- .github/workflows/integration.yml
- Makefile
- test/common/gitops_utils.go
- test/common/gvr.go
- test/integration/policy_generator_acm_hardening_test.go
- test/integration/policy_generator_helm_test.go
- test/integration/policy_generator_remote_test.go
- test/integration/policy_generator_test.go
- test/resources/policy_generator/helm-kustomization/base/kustomization.yaml
- test/resources/policy_generator/subscription-helm.yaml
Confirmed that `kustomize` internally uses `helm template`:
https://github.com/kubernetes-sigs/kustomize/blob/91ccf00ac8f787551eb4c5baad486b088ef3737b/api/types/helmchartargs.go#L149
Which doesn't call the Kubernetes API, so security here should be fine, but we have a `lookup` in the chart just to make sure:
```shell
$ helm template --help
Render chart templates locally and display the output.
Any values that would normally be looked up or retrieved in-cluster will be
faked locally. Additionally, none of the server-side testing of chart validity
(e.g. whether an API is supported) is done.
```
ref: https://issues.redhat.com/browse/ACM-9456
> Add integration tests: Helm in the PolicyGenerator

- .github/workflows/repo-config.yml
The source is definitely some unescaped quotation marks in the JSON, so we'll see whether escaping them works...
> Fix ci status check

- test/common/gvr.go
- test/integration/compliance_history_test.go
- test/resources/compliance_history/compliance-api-prerequisites.yaml
- test/resources/compliance_history/policy.yaml
- test/resources/compliance_history/service_account.yaml
The test creates a policy that applies to all clusters. It has one configuration policy that is always compliant and the other configuration policy is always noncompliant. The test verifies that these compliance events are present on the compliance history API for every managed cluster.
Relates:
https://issues.redhat.com/browse/ACM-10033
> Add a SVT test for compliance history

- .github/workflows/integration.yml
- .github/workflows/kind.yml
With the updated propagator, Go v1.21 is a requirement, but Go v1.20 is currently the default in GitHub Actions.
> Set Go version for Integration Test

- .gitignore
- build/clean-up-cluster.sh
- test/integration/compliance_history_test.go
- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/resources/compliance_history/policy-uninstall-gk.yaml
ref: https://issues.redhat.com/browse/ACM-10556
There were some competing causes to the flakiness for these tests:
- We ran into an unrecoverable OLM caching bug outlined in https://access.redhat.com/solutions/6991414, solved by restarting the OLM pods
- The compliance history Gatekeeper cleanup Policy was not getting deleted, causing it to linger and continuously clean up when the Gatekeeper test would run (possibly causing the unrecoverable state?)
- Cleanup commands in Gatekeeper were also getting skipped because not all resources had been deployed and it didn't tolerate that.
The cleanup script was also only cleaning up in certain namespaces when the Gatekeeper cleanup policy had been deployed to the global-set namespace. This updates the commands to clean up policies aggressively …
> Fix Gatekeeper operator cleanup

- test/resources/compliance_history/policy-gk-prereq2.yaml
The ConfigurationPolicy names must match in `policy-gk-prereq.yaml` and `policy-gk-prereq2.yaml`.
> Fix the compliance history configuration policy name

- test/integration/compliance_history_test.go
Increase verifyPolicyOnAllClusters timeout from 30 secs to 60 secs as we discussed
Ref: https://redhat-internal.slack.com/archives/CUS1VB8P3/p1712154840798339
> Increase verify policy on all clusters func timeout

- build/codebase-check.sh
- build/common.sh
The diff will still be in the workflow logs and summary, but it's too long for things like Slack messages.
> Remove diff from output

- test/integration/compliance_history_test.go
- test/resources/compliance_history/cert-prereq.yaml
The auto cherry-pick has failed. 
- Change the adding cert secret from command to policy
- Increase timeout for compliance API to be ready
- Wait for namespace in history tests
> Manual cherry pick 2.10

- build/common.sh
If `SKIP_CLONING` is set, the token isn't required.
Followup to:
- #784
> Fix variable check

- test/common/policy_utils.go
- test/integration/compliance_history_test.go
- test/integration/policy_install_operator_test.go
The new `RegisterDebugMessage` is based off of a pattern that is working well in the config-policy-controller tests in order to only print certain debug information when the test fails. This is especially useful in `Eventually` assertions.
This updates several tests to use this new function which will hopefully help in debugging some inconsistent tests.
Refs:
- https://github.com/stolostron/backlog/issues/27556
- https://github.com/stolostron/backlog/issues/27558
2nd Commit:
Combine operator tests for sub, csv, and deploy
This test was running inconsistently because depending on how quickly OLM finds and applies the possible upgrade for the operator, the test was sometimes looking for an older CSV.
Refs:
- https://github.com/stolostron/backlog/issues/27561
- …
> Add some debug messages and address some flaky tests

- test/integration/policy_install_operator_test.go
- test/resources/operator_policy/test-op-err-correct.yaml
- test/resources/operator_policy/test-op-err-initial.yaml
- test/resources/policy_install_operator/operator_policy_no_group.yaml
- test/resources/policy_install_operator/operator_policy_with_group.yaml
Since the tests don't test upgrades, it's more reliable to have OLM pick the latest on the channel rather than have it potentially upgrade.
Relates:
https://github.com/stolostron/backlog/issues/27575
> Remove startingCSV from the test operator policies

- Makefile
- build/run-e2e-tests-policy-framework-prow.sh
- build/run-test-image.sh
- test/common/common.go
- test/integration/integration_suite_test.go
- test/integration/policy_certificate_test.go
- test/integration/policy_comp_operator_test.go
- test/integration/policy_etcdencryption_test.go
- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/integration/policy_imagemanifest_test.go
- test/integration/policy_limitmemory_test.go
- test/integration/policy_namespace_test.go
- test/integration/policy_pod_test.go
- test/integration/policy_psp_test.go
- test/integration/policy_role_test.go
- test/integration/policy_rolebinding_test.go
- test/integration/policy_scc_test.go
- test/integration/policy_zts_cmc_test.go
This will allow the IAM policy tests to still work on 2.10 and earlier.
Relates:
https://issues.redhat.com/browse/ACM-10859
https://github.com/stolostron/canary-scripts/pull/297
https://github.com/stolostron/governance-policy-framework/pull/796
> Use the matching release branch on the policy-collection

- test/integration/compliance_history_test.go
Specifically, the CSV name is now listed in the message.
> Handle the operator policy message changes

- build/import-managed.sh
```
error: jsonpath wait format must be --for=jsonpath='{.status.readyReplicas}'=3
error: unknown flag: --all
See 'kubectl get --help' for usage.
```
ref: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/51057/rehearse-51057-pull-ci-stolostron-governance-policy-framework-main-test-e2e-grc-framework/1788621143599484928/artifacts/test-e2e-grc-framework/e2e/build-log.txt
The `wait` command works for me locally, so I'm not sure whether there's just an older `kubectl` version in the CI...
> Fix import ManagedCluster script

- test/integration/operator_policy_error_test.go
- test/resources/compliance_history/operator-policy-invalid.yaml
- test/resources/compliance_history/policy-install-gk.yaml
- test/resources/operator_policy/test-op-err-correct.yaml
- test/resources/operator_policy/test-op-err-initial.yaml
- test/resources/policy_install_operator/operator_policy_all_defaults.yaml
- test/resources/policy_install_operator/operator_policy_no_group.yaml
- test/resources/policy_install_operator/operator_policy_with_group.yaml
Per a recent change in the controller, it is now invalid to specify installPlanApproval in an OperatorPolicy, and it is necessary to specify upgradeApproval.
Refs:
- https://github.com/open-cluster-management-io/config-policy-controller/pull/249
> Update OperatorPolicy tests for upgradeApproval

- test/resources/policy_install_operator/operator_policy_all_defaults.yaml
- test/resources/policy_install_operator/operator_policy_no_group.yaml
- test/resources/policy_install_operator/operator_policy_with_group.yaml
When a cluster is imported but not available due to a failed deployment, the policy can never become compliant.
Relates:
https://github.com/stolostron/backlog/issues/27628
> Skip unavailable clusters in OperatorPolicy defaults test

- build/periodic-slack-report.sh
Getting the CURRENT_VERSION needs to be done before changing into the artifacts directory.
> Fix periodic-slack-report.sh CURRENT_VERSION

- test/resources/compliance_history/cert-policy.yaml
- test/resources/compliance_history/cert-prereq.yaml
- test/resources/compliance_history/operator-policy-invalid.yaml
- test/resources/compliance_history/operator-prereq.yaml
- test/resources/compliance_history/policy-gk-prereq.yaml
- test/resources/compliance_history/policy-gk-prereq2.yaml
- test/resources/compliance_history/policy-gk.yaml
- test/resources/compliance_history/policy-install-gk.yaml
- test/resources/compliance_history/policy-uninstall-gk.yaml
- test/resources/compliance_history/policy.yaml
- test/resources/policy_install_operator/clean-up-grcqeoptest-ns.yaml
- test/resources/policy_install_operator/operator_policy_all_defaults.yaml
- test/resources/policy_install_operator/operator_policy_no_group.yaml
- test/resources/policy_install_operator/operator_policy_with_group.yaml
- test/resources/recreate_option/policy-configmap.yaml
- test/resources/recreate_option/policy-initial-deployment.yaml
- test/resources/recreate_option/policy-update-deployment.yaml
This will help in the tests that apply to all clusters since sometimes a managed cluster fails to fully provision but still gets selected.
> Filter out clusters where GRC is unavailable

- test/integration/verify_metrics_test.go
This was removed as part of making config-policy-controller event-driven.
> Remove the config_policies_evaluation_duration metric from the test

- test/common/common.go
- test/common/gitops_utils.go
- test/common/policy_utils.go
- test/e2e/cert_policy_test.go
- test/e2e/configuration_policy_test.go
- test/integration/compliance_history_test.go
- test/integration/integration_suite_test.go
- test/integration/verify_metrics_test.go
Also:
- Passes `SpecContext` to metrics test, GitOps setup functions,  and Before/After suites.
- Adds additional description to metrics test.
> Replace `WithOffset()` with `GinkgoHelper()`

- test/e2e/hub_templates_encryption_test.go
This will allow us to potentially reproduce the issue in a local environment.
> Output the policy-encryption-key when debugging a test failure

- test/integration/compliance_history_test.go
- test/resources/compliance_history/policy-uninstall-gk.yaml
Only the "real" CSV in the subscription namespace needs to be deleted. The others are copies that get cleaned up automatically. This should make the test faster and more stable.
> Simplify the Gatekeeper uninstall

- test/integration/compliance_history_test.go
- test/integration/policy_gatekeeper_operator_downstream_test.go
- test/resources/gatekeeper/policy-uninstall-gk.yaml
This leverages OperatorPolicy to uninstall the Gatekeeper operator along with some ConfigurationPolicy to remove other related objects.
Relates:
https://issues.redhat.com/browse/ACM-13584
> Fix the Gatekeeper operator uninstall

- test/integration/policy_install_operator_test.go
- test/resources/policy_install_operator/operator_policy_no_group_templated_versions.yaml
Relates:
https://issues.redhat.com/browse/ACM-15658
> Add a test for OperatorPolicy spec.versions templating

- test/common/gvr.go
- test/integration/addon_configuration_test.go
- test/resources/addon_configuration/addondeploymentconfig.yaml
- test/resources/addon_configuration/cmao_config_patch.json
- test/resources/addon_configuration/cmao_restore_patch.json
- test/resources/addon_configuration/mcao_config_patch.json
- test/resources/addon_configuration/mcao_restore_patch.json
I made this an SVT because restarting the Pods could be disruptive to other tests, and also would wipe any logs.
ref: https://issues.redhat.com/browse/ACM-17979
> Add test for configuring add-ons

- .ci-operator.yaml
- .github/workflows/kind.yml
- build/Dockerfile.e2etest
- build/common/Makefile.common.mk
- go.mod
- go.sum
- test/integration/compliance_history_test.go
> [release-2.11] Address `oauth2` vuln

- test/integration/standalone_hubtemplates_test.go
- test/resources/standalone_hubtemplates/config-standalone-addon.yaml
- test/resources/standalone_hubtemplates/config-standalone-rbac.yaml
- test/resources/standalone_hubtemplates/standalone-hubtemplates-test-updated.yaml
- test/resources/standalone_hubtemplates/standalone-hubtemplates-test.yaml
The test verifies the special message emitted when the addon is not enabled, as well as behavior around configuring "special" RBAC.
Refs:
- https://issues.redhat.com/browse/ACM-16137
- https://issues.redhat.com/browse/ACM-16094
> Add SVT test for standalone-hub-templating

- test/integration/policy_selector_test.go
ref: https://issues.redhat.com/browse/ACM-19753
> Add test for `skipObject` with an argument

- build/codebase-check.sh
The quotes were meant to fix a Shellcheck error but the args aren't getting split up properly and being parsed as a long string instead of two separate string args:
```
tee: '/home/runner/work/governance-policy-framework/governance-policy-framework/codebase-errors.log /home/runner/work/governance-policy-framework/governance-policy-framework/summary-codebase-errors.log': No such file or directory
```
Followup to:
- #927
> fix: Pass codebase check files as array

- build/common/Makefile.common.mk
The original gocovmerge breaks sometimes when new versions of Go are released.
It might be worth moving some repository tests to the newer coverprofile directory format, but moving to a fork might make CI more stable for existing release branches.
> Use a gocovmerge fork
